/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const AuthorView = (props) => {
	return <>
		<div>boxId: {props.boxId !== null && props.boxId !== undefined ? props.boxId.toString() : ""}</div>
		<div>reverse: {props.reverse !== null && props.reverse !== undefined ? props.reverse.toString() : ""}</div>
		{props.children}
	</> 
}



/******* S.D.G. *******/



