/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../AppUtils";
import {Texts} from "../../../app/Texts";


export const BoxSettingsView = (props) => {
	return <div className="form">
		<h1>{translate(Texts.boxSettings.title)}</h1>
		{props.children}
	</div>
}



/******* S.D.G. *******/



