/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const BoxSettingsView = (props) => {
	return <>
		{props.children}
	</>
}



/******* S.D.G. *******/



