/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import React from "react";
import {BoxSettings} from "./boxSettingsView/BoxSettings";


export const BoxSettingsView = (props) => {
	return <BoxSettings {...props.boxSettings} language={props.language}/>
}



/******* S.D.G. *******/



