/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const DashboardView = (props) => {
	return <>
		{props.children}
	</> 
}



/******* S.D.G. *******/



