/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";


export const DashboardView = (props) => {
    return <div id="dashboard" className="dashboard">
        {props.children}
    </div>
}


/******* S.D.G. *******/



