/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";


export const DashboardView = (props) => {
    return <div id="dashboard">
        <div className="bottomMargin">
            {props.children}
        </div>
    </div>
}


/******* S.D.G. *******/



