/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const ForgotPasswordView = (props) => {
	return <>
		<div>username: {props.username !== null && props.username !== undefined ? props.username.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



