/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../app/Texts";
import {login, passwordChanged, toggleSaveInLocalStorage, usernameChanged} from "../../../../gen/login/ActionFunctions";
import {route} from "../../../../gen/common/ActionFunctions";
import CryptoJS from "crypto-js";
import {translate} from "../../../AppUtils";


export const LoginView = () => {
	// noinspection JSUnresolvedFunction
	return <div className="center form">
		<h1>{translate(Texts.login.title)}</h1>
		<div className="line">
			<label htmlFor="username">
				{translate(Texts.login.username)}
			</label>
			<input
				id="username"
				type="text"
				onChange={(e) => usernameChanged(e.target.value)}
				autoComplete="username"
			/>
			<a id="registration" onClick={() => route("#registration")}>{translate(Texts.login.registration)}</a>
		</div>
		<div className="line">
			<label htmlFor="password">
				{translate(Texts.login.password)}
			</label>
			<input
				id="password"
				type="password"
				onChange={(e) => passwordChanged(CryptoJS.MD5(e.target.value).toString())}
				autoComplete="current-password"
			/>
			<a onClick={() => route("#forgotpassword")}>{translate(Texts.login.forgotPassword)}</a>
		</div>
		<div className="line">
			<input
				id="saveInLocalStorage"
				type="checkbox"
				onChange={toggleSaveInLocalStorage}
			/>
			<label htmlFor="saveInLocalStorage">
				{translate(Texts.login.saveInLocalStorage)}
			</label>
			<div className="small-font">{translate(Texts.login.saveInLocalStorageHint)}</div>
		</div>
		<div className="moreMarginLine hCenter">
			<button
				className="primary"
				id="login"
				onClick={login}
			>
				{translate(Texts.login.signin)}
			</button>
		</div>
	</div>
}



/******* S.D.G. *******/



