/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

export const PrivacyPolicyView = (props) => {
    return <div className="center privacy-policy">
        <h1>Datenschutzerklärung</h1>
        <h2>Speicherung von Daten in Log-Dateien</h2>
        <p>Um den Betrieb dieser Website sicherzustellen, werden IP-Adresse, Zeitpunkt des Zugriffs und Typ und Version
            des verwendeten Browsers in Log-Dateien gespeichert.</p>
        <h2>Speicherung personenbezogener Daten in einer Datenbank</h2>
        <p>
            Registriert sich ein Benutzer bei der Plattform, werden personenbezogenen Daten in einer Datenbank, die
            bei <a
            href="https://www.hetzner.com/de/cloud"
            target="hetzner"
        >
            Hetzner
        </a> auf einem Cloud-Server liegt, gespeichert. Dies ist nötig, um ihm den Zugriff auf seinen persönlichen
            Bereich zu gewährleisten.
        </p>
        <h2>Keine Verwendung von Cookies</h2>
        <p>Diese Website verwendet keine Cookies und analysiert auch keine Daten zu Marketingzwecken. Lediglich wenn der
            Benutzer angemeldet bleiben möchte, werden die Login-Daten gespeichert. Das Passwort wir dabei
            verschlüsselt.</p>
        <h2>Keine Anbindung an soziale Netzwerke</h2>
        <p>Diese Website ist mit keinem sozialen Netzwerk verbunden.</p>
        <p>
            <a onClick={(event) => props.onClick()}>
                Zurück
            </a>
        </p>
    </div>
}


/******* S.D.G. *******/



