/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const ProfileView = (props) => {
	return <>
		<div>username: {props.username !== null && props.username !== undefined ? props.username.toString() : ""}</div>
		<div>email: {props.email !== null && props.email !== undefined ? props.email.toString() : ""}</div>
		<div>role: {props.role !== null && props.role !== undefined ? props.role.toString() : ""}</div>
		<div>showDeleteUserDialog: {props.showDeleteUserDialog !== null && props.showDeleteUserDialog !== undefined ? props.showDeleteUserDialog.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



