/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../AppUtils";
import {Texts} from "../../../app/Texts";
import {Modal} from "../../common/Modal";

export const ProfileView = (props) => {
	if (props.username === undefined) {
		return null;
	}
	return <div className="form">
		{props.showDeleteUserDialog === true &&
			<Modal
				title={translate(Texts.profile.confirmDelete.title)}
				message={translate(Texts.profile.confirmDelete.message)}
				confirm={translate(Texts.profile.confirmDelete.ok)}
				cancel={translate(Texts.profile.confirmDelete.cancel)}
				onConfirm={props.deleteUser}
				onCancel={props.deleteUserCancel}
			/>
		}
		<h1>{translate(Texts.profile.title)}</h1>
		{props.children}
	</div>
}



/******* S.D.G. *******/



