/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../AppUtils";
import {Texts} from "../../../app/Texts";
import {Modal} from "../../common/Modal";


export const ProfileView_bak = (props) => {
	if (props.username === undefined) {
		return null;
	}
	return <div className="center-wide">
		{props.showDeleteUserDialog === true &&
			<Modal
				title={translate(Texts.profile.confirmDelete.title)}
				message={translate(Texts.profile.confirmDelete.message)}
				confirm={translate(Texts.profile.confirmDelete.ok)}
				cancel={translate(Texts.profile.confirmDelete.cancel)}
				onConfirm={props.deleteUser}
				onCancel={props.deleteUserCancel}
			/>
		}
		<div className="form">
			<h1>
				<button onClick={props.routeToDefault}><i className="fa fa-arrow-left"/></button>
				{translate(Texts.profile.title)}
			</h1>
			<div className="line">
				<label htmlFor="username">{translate(Texts.profile.username)}</label>
				<div className="inputContainer">
					<input
						type="text"
						value={props.username}
						id="username"
						readOnly={true}
					/>
				</div>
			</div>
			<div className="line">
				<label htmlFor="email">{translate(Texts.profile.email)}</label>
				<div className="inputContainer">
					<input
						type="text"
						value={props.email}
						id="email"
						readOnly={true}
					/>
				</div>
			</div>
			<div className="moreMarginLine text-center">
				<button
					className="danger"
					onClick={props.deleteUserClick}
					disabled={!props.deletable}
				>
					{translate(Texts.profile.delete)}
				</button>
			</div>
		</div>
	</div>

}



/******* S.D.G. *******/



