/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../app/Texts";
import {deleteUser, deleteUserCancel, deleteUserClick} from "../../../../gen/profile/ActionFunctions";
import {route} from "../../../../gen/common/ActionFunctions";
import {translate} from "../../../AppUtils";


export const ProfileView = (props) => {
	if (props.username === undefined) {
		return null;
	}
	return <div className="center-wide">
		{props.showDeleteUserDialog === true ?
			<div className="modal">
				<div className="modalContent danger">
					<h2>{translate(Texts.profile.confirmDelete.title)}</h2>
					<div className="message">{translate(Texts.profile.confirmDelete.message)}</div>
					<button
						className="yes"
						onClick={deleteUser}
					>
						{translate(Texts.profile.confirmDelete.ok)}
					</button>
					<button
						onClick={deleteUserCancel}
					>
						{translate(Texts.profile.confirmDelete.cancel)}
					</button>
				</div>
			</div> :
			null
		}
		<div className="form">
			<h1>
				<button onClick={() => route("#dashboard")}><i className="fa fa-arrow-left"/></button>
				{translate(Texts.profile.title)}
			</h1>
			<div className="line">
				<label htmlFor="username">{translate(Texts.profile.username)}</label>
				<div className="inputContainer">
					<input
						type="text"
						value={props.username}
						id="username"
						readOnly={true}
					/>
				</div>
			</div>
			<div className="line">
				<label htmlFor="email">{translate(Texts.profile.email)}</label>
				<div className="inputContainer">
					<input
						type="text"
						value={props.email}
						id="email"
						readOnly={true}
					/>
				</div>
			</div>
			<div className="moreMarginLine hCenter">
				<button
					className="danger"
					onClick={deleteUserClick}
				>
					{translate(Texts.profile.delete)}
				</button>
			</div>
		</div>
	</div>
}



/******* S.D.G. *******/



