/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import React from "react";
import {route} from "../../../../gen/common/ActionFunctions";
import {NextCard} from "./queryCardView/NextCard";


export const QueryCardView = (props) => {
    const progress = () => {
        const open = Math.round(props.openTodaysCards / props.allTodaysCards * 100);
        const done = 100 - open;
        return <div className="progress">
            <div
                className={`${done === 100 ? 'all-done' : 'done'}`}
                style={{width: `${done}%`}}
            />
            <div
                className={`${open === 100 ? 'all-open' : 'open'}`}
                style={{width: `${open}%`}}
            />
        </div>
    }

    return <div className="box">
        <h1>
            <button
                className="backButton"
                onClick={() => route("#dashboard")}
            >
                <i className="fa fa-arrow-left"/>
            </button>
            <span>{props.categoryName} {props.reverse ?
                <i className="fas fa-arrows-alt-h withmarginleft"/> : null}</span>
        </h1>
        {progress()}
        {props.openTodaysCards > 0 && <NextCard enableScoreButtons={props.enableScoreButtons} reverse={props.reverse} language={props.language} {...props.nextCard} />}
    </div>
}

/******* S.D.G. *******/



