/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const QueryCardView = (props) => {
	return <>
		<div>openTodaysCards: {props.openTodaysCards !== null && props.openTodaysCards !== undefined ? props.openTodaysCards.toString() : ""}</div>
		<div>allTodaysCards: {props.allTodaysCards !== null && props.allTodaysCards !== undefined ? props.allTodaysCards.toString() : ""}</div>
		<div>reverse: {props.reverse !== null && props.reverse !== undefined ? props.reverse.toString() : ""}</div>
		<div>enableScoreButtons: {props.enableScoreButtons !== null && props.enableScoreButtons !== undefined ? props.enableScoreButtons.toString() : ""}</div>
		<div>boxId: {props.boxId !== null && props.boxId !== undefined ? props.boxId.toString() : ""}</div>
		{props.children}
	</> 
}



/******* S.D.G. *******/



