/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import "./queryCard.scss";

export const QueryCardView = (props) => {
    const progress = () => {
        const open = Math.round(props.openTodaysCards / props.allTodaysCards * 100);
        const done = 100 - open;
        return <div className="progress">
            <div style={{width: `${done}%`}} className="doneContainer">
                <div
                    className="done"
                />
            </div>
        </div>
    }

    if (!props.nextCard) {
        return null
    }

    return <div className="box">
        <div className="boxHeader">
            <button
                className="primary"
                onClick={props.routeToDefault}
            >
                <i className="fa fa-arrow-left"/>
            </button>
            <h2>
                {props.boxName} {props.reverse ?
                <i className="fas fa-arrows-alt-h withmarginleft"/> : null}
            </h2>
        </div>
        {progress()}
        {props.children}
    </div>
}

/******* S.D.G. *******/



