/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../AppUtils";
import {Texts} from "../../../app/Texts";


export const RegistrationView = (props) => {
    if (props.username === undefined) {
        return null;
    }
    return (
        <div className="form">
            <h1>{translate(Texts.registration.title)}</h1>
            {props.children}
        </div>
    )
}


/******* S.D.G. *******/



