/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../AppUtils";
import {Texts} from "../../../app/Texts";


export const RegistrationView = (props) => {
    if (props.username === undefined) {
        return null;
    }
    return (
        <div className="center">
            <div className="form">
                <h1>{translate(Texts.registration.title)}</h1>
                {props.children}
                <div className="line">
                    <div
                        className="small-font">{translate(Texts.registration.terms)}</div>
                </div>
            </div>
        </div>
    )
}


/******* S.D.G. *******/



