/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const ResetPasswordView = (props) => {
	return <>
		<div>token: {props.token !== null && props.token !== undefined ? props.token.toString() : ""}</div>
		<div>password: {props.password !== null && props.password !== undefined ? props.password.toString() : ""}</div>
		<div>passwordRepetition: {props.passwordRepetition !== null && props.passwordRepetition !== undefined ? props.passwordRepetition.toString() : ""}</div>
		<div>passwordMismatch: {props.passwordMismatch !== null && props.passwordMismatch !== undefined ? props.passwordMismatch.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



