/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractResetPasswordCommand from "../../../gen/password/commands/AbstractResetPasswordCommand";
import * as AppUtils from "../../AppUtils";

export default class ResetPasswordCommand extends AbstractResetPasswordCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.hash = "#";
        data.message = AppUtils.createInfoMessage("passwordReset");
        this.addOkOutcome(data);
        resolve(data);
    }
    handleError(data, resolve) {
        data.hash = "#";
        this.addErrorOutcome(data);
        resolve(data);
    }
}




/******* S.D.G. *******/

