/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractValidateUsernameCommand from "../../../gen/password/commands/AbstractValidateUsernameCommand";

export default class ValidateUsernameCommand extends AbstractValidateUsernameCommand {
    execute(data) {
        data.disabled = !data.username || data.username && data.username.length === 0
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



