/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCollapseTreeItemInMoveDialogCommand from "../../../gen/category/commands/AbstractCollapseTreeItemInMoveDialogCommand";
import {collapseTreeItem} from "./CollapseTreeItemCommand";

export default class CollapseTreeItemInMoveDialogCommand extends AbstractCollapseTreeItemInMoveDialogCommand {
    execute(data) {
        return collapseTreeItem(data, data.rootCategoryInMoveDialog, this.addOkOutcome, this.addSelectParentCategoryOutcome);
    }
}




/******* S.D.G. *******/



