/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateReverseBoxCommand from "../../../gen/category/commands/AbstractCreateReverseBoxCommand";

export default class CreateReverseBoxCommand extends AbstractCreateReverseBoxCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



