/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateCategoryCommand from "../../../gen/category/commands/AbstractCreateCategoryCommand";

export default class CreateCategoryCommand extends AbstractCreateCategoryCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.selectedCategoryId = data.parentCategoryId;
        data.categoryIdToBeExpanded = data.parentCategoryId;
        data.categoryDialog = null;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



