/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractExpandTreeItemInMoveDialogCommand from "../../../gen/category/commands/AbstractExpandTreeItemInMoveDialogCommand";
import {expandTreeItem} from "./ExpandTreeItemCommand";

export default class ExpandTreeItemInMoveDialogCommand extends AbstractExpandTreeItemInMoveDialogCommand {
    execute(data) {
        return expandTreeItem(data, data.rootCategoryInMoveDialog, this.addOkOutcome);
    }
}




/******* S.D.G. *******/



