/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractExpandTreeItemCommand from "../../../gen/category/commands/AbstractExpandTreeItemCommand";
import {findCategory} from "../utils/CategoryTreeUtils"

export const expandTreeItem = (data, rootCategory, addOkOutcome) => {
    let category = findCategory(rootCategory.childCategories, data.categoryId);
    category.expanded = true;
    addOkOutcome(data);
    return data;
}

export default class ExpandTreeItemCommand extends AbstractExpandTreeItemCommand {
    execute(data) {
        return expandTreeItem(data, data.rootCategory, this.addOkOutcome);
    }
}




/******* S.D.G. *******/

