/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractInviteUserNextStepCommand from "../../../gen/category/commands/AbstractInviteUserNextStepCommand";

export default class InviteUserNextStepCommand extends AbstractInviteUserNextStepCommand {
    execute(data) {
        data.inviteUserDialog = {
            display: false,
            usernameSearchString: ""
        };
        data.inviteUserEditableDialog = {
            display: true,
            editable: data.editable,
            invitedUsername: data.invitedUsername
        };
        this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



