/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCategoryClickedCommand from "../../../gen/category/commands/AbstractMoveCategoryClickedCommand";

export default class MoveCategoryClickedCommand extends AbstractMoveCategoryClickedCommand {
    execute(data) {
        data.moveCategory = {
            display: true,
            rootCategoryInMoveDialog: structuredClone(data.rootCategory),
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



