/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCategoryAllowedCommand from "../../../gen/category/commands/AbstractMoveCategoryAllowedCommand";
import {isCategoryChildOfParent} from "../utils/CategoryTreeUtils";

export default class MoveCategoryAllowedCommand extends AbstractMoveCategoryAllowedCommand {
    execute(data) {
        if (data.target) {
            const movedCategoryIsNotRootCategory = data.rootCategory.categoryId !== data.toBeMoved.categoryId
            const targetIsNotSameAsMoved = data.toBeMoved.categoryId !== data.target.categoryId;
            const targetIsNotSameAsParentOfMoved = data.target.categoryId !== data.toBeMoved.parentCategoryId;
            const targetIsNotChildOfMoved = !isCategoryChildOfParent(data.toBeMoved, data.target.categoryId);
            data.moveAllowed = movedCategoryIsNotRootCategory
                && targetIsNotSameAsMoved
                && targetIsNotSameAsParentOfMoved
                && targetIsNotChildOfMoved;
        } else {
            data.moveAllowed = false;
        }
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



