/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCategoryCancelledCommand from "../../../gen/category/commands/AbstractMoveCategoryCancelledCommand";

export default class MoveCategoryCancelledCommand extends AbstractMoveCategoryCancelledCommand {
    execute(data) {
        data.moveCategory = {
            display: false,
            rootCategoryInMoveDialog: null,
        };
        this.addOkOutcome(data);
        return data;
    }
}




/******* S.D.G. *******/



