/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractSelectTargetCategoryCommand from "../../../gen/category/commands/AbstractSelectTargetCategoryCommand";
import {selectTreeItem} from "./SelectTreeItemCommand";

export default class SelectTargetCategoryCommand extends AbstractSelectTargetCategoryCommand {
    execute(data) {
        return selectTreeItem(data, data.rootCategoryInMoveDialog, this.addOkOutcome);
    }
}




/******* S.D.G. *******/



