/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSelectTreeItemCommand from "../../../gen/category/commands/AbstractSelectTreeItemCommand";
import {findCategory} from "../utils/CategoryTreeUtils";

export const selectTreeItem = (data, rootCategory, addOkOutcome) => {
    if (rootCategory.categoryId === data.categoryId) {
        data.selectedCategory = rootCategory;
    } else {
        data.selectedCategory = findCategory(rootCategory.childCategories, data.categoryId);
    }
    addOkOutcome(data);
    return data;
}

export default class SelectTreeItemCommand extends AbstractSelectTreeItemCommand {
    execute(data) {
        return selectTreeItem(data, data.rootCategory, this.addOkOutcome);
    }
}




/******* S.D.G. *******/



