/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractToggleCategoryOrderCommand from "../../../gen/category/commands/AbstractToggleCategoryOrderCommand";

export default class ToggleCategoryOrderCommand extends AbstractToggleCategoryOrderCommand {

    validateCommandData(data) {
        if (data.down === undefined) {
            data.down = true;
        }
    	return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



