/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractArchiveBoxAction from "../../../gen/box/actions/AbstractArchiveBoxAction";

export default class ArchiveBoxAction extends AbstractArchiveBoxAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



