/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCallScoreReinforceCardAction from "../../../gen/box/actions/AbstractCallScoreReinforceCardAction";

export default class CallScoreReinforceCardAction extends AbstractCallScoreReinforceCardAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



