/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCallSortCardOutAction from "../../../gen/box/actions/AbstractCallSortCardOutAction";

export default class CallSortCardOutAction extends AbstractCallSortCardOutAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



