/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCallScoreCardAction from "../../../gen/box/actions/AbstractCallScoreCardAction";

export default class CallScoreCardAction extends AbstractCallScoreCardAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



