/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCategoryNameChangedAction from "../../../gen/box/actions/AbstractCategoryNameChangedAction";

export default class CategoryNameChangedAction extends AbstractCategoryNameChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



