/********************************************************************************
 * generated by de.acegen 1.6.5
 ********************************************************************************/




import AbstractFilterActiveCardListWithLastQualityChangedAction from "../../../gen/box/actions/AbstractFilterActiveCardListWithLastQualityChangedAction";

export default class FilterActiveCardListWithLastQualityChangedAction extends AbstractFilterActiveCardListWithLastQualityChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



