/********************************************************************************
 * generated by de.acegen 1.6.5
 ********************************************************************************/




import AbstractFilterActiveCardListAction from "../../../gen/box/actions/AbstractFilterActiveCardListAction";

export default class FilterActiveCardListAction extends AbstractFilterActiveCardListAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



