/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractInitBoxesForDayDuringScoreAction from "../../../gen/box/actions/AbstractInitBoxesForDayDuringScoreAction";

export default class InitBoxesForDayDuringScoreAction extends AbstractInitBoxesForDayDuringScoreAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



