/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractInitBoxesForDayAction from "../../../gen/box/actions/AbstractInitBoxesForDayAction";

export default class InitBoxesForDayAction extends AbstractInitBoxesForDayAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



