/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractLoadBoxesAction from "../../../gen/box/actions/AbstractLoadBoxesAction";

export default class LoadBoxesAction extends AbstractLoadBoxesAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



