/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadSettingsAction from "../../../gen/box/actions/AbstractLoadSettingsAction";

export default class LoadSettingsAction extends AbstractLoadSettingsAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



