/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractLoadBoxStatisticsAction from "../../../gen/box/actions/AbstractLoadBoxStatisticsAction";

export default class LoadBoxStatisticsAction extends AbstractLoadBoxStatisticsAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



