/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractLoadNextCardAction from "../../../gen/box/actions/AbstractLoadNextCardAction";

export default class LoadNextCardAction extends AbstractLoadNextCardAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



