/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractRootCategoryNameChangedAction from "../../../gen/box/actions/AbstractRootCategoryNameChangedAction";

export default class RootCategoryNameChangedAction extends AbstractRootCategoryNameChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



