/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractScheduleSelectedCardsAction from "../../../gen/box/actions/AbstractScheduleSelectedCardsAction";

export default class ScheduleSelectedCardsAction extends AbstractScheduleSelectedCardsAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



