/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractScoreCardAction from "../../../gen/box/actions/AbstractScoreCardAction";

export default class ScoreCardAction extends AbstractScoreCardAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



