/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractSelectScheduleCardRangeAction from "../../../gen/box/actions/AbstractSelectScheduleCardRangeAction";

export default class SelectScheduleCardRangeAction extends AbstractSelectScheduleCardRangeAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



