/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractTooManyCardsStatusAction from "../../../gen/box/actions/AbstractTooManyCardsStatusAction";

export default class TooManyCardsStatusAction extends AbstractTooManyCardsStatusAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



