/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateCardPriorityAction from "../../../gen/box/actions/AbstractUpdateCardPriorityAction";

export default class UpdateCardPriorityAction extends AbstractUpdateCardPriorityAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



