/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCallSaveBugAction from "../../../gen/common/actions/AbstractCallSaveBugAction";

export default class CallSaveBugAction extends AbstractCallSaveBugAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



