/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDisplayVersionMismatchDialogAction from "../../../gen/common/actions/AbstractDisplayVersionMismatchDialogAction";

export default class DisplayVersionMismatchDialogAction extends AbstractDisplayVersionMismatchDialogAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



