/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDisplayVersionMismatchErrorDialogAction from "../../../gen/common/actions/AbstractDisplayVersionMismatchErrorDialogAction";

export default class DisplayVersionMismatchErrorDialogAction extends AbstractDisplayVersionMismatchErrorDialogAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



