/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractDisplayErrorToastAction from "../../../gen/common/actions/AbstractDisplayErrorToastAction";

export default class DisplayErrorToastAction extends AbstractDisplayErrorToastAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



