/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetUserInfoAction from "../../../gen/common/actions/AbstractGetUserInfoAction";

export default class GetUserInfoAction extends AbstractGetUserInfoAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



