/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractHideToastAction from "../../../gen/common/actions/AbstractHideToastAction";

export default class HideToastAction extends AbstractHideToastAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



