/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToSelectedCategoryAction from "../../../gen/common/actions/AbstractRouteToSelectedCategoryAction";

export default class RouteToSelectedCategoryAction extends AbstractRouteToSelectedCategoryAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



