/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToBoxSettingsAction from "../../../gen/common/actions/AbstractRouteToBoxSettingsAction";

export default class RouteToBoxSettingsAction extends AbstractRouteToBoxSettingsAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



