/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToActiveCardsAction from "../../../gen/common/actions/AbstractRouteToActiveCardsAction";

export default class RouteToActiveCardsAction extends AbstractRouteToActiveCardsAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



