/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToDefaultAction from "../../../gen/common/actions/AbstractRouteToDefaultAction";

export default class RouteToDefaultAction extends AbstractRouteToDefaultAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



