/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToPrivacyPolicyAction from "../../../gen/common/actions/AbstractRouteToPrivacyPolicyAction";

export default class RouteToPrivacyPolicyAction extends AbstractRouteToPrivacyPolicyAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



