/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToRegistrationAction from "../../../gen/common/actions/AbstractRouteToRegistrationAction";

export default class RouteToRegistrationAction extends AbstractRouteToRegistrationAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



