/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToHomeAction from "../../../gen/common/actions/AbstractRouteToHomeAction";

export default class RouteToHomeAction extends AbstractRouteToHomeAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



