/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToAuthorViewAction from "../../../gen/common/actions/AbstractRouteToAuthorViewAction";

export default class RouteToAuthorViewAction extends AbstractRouteToAuthorViewAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



