/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToProfileViewAction from "../../../gen/common/actions/AbstractRouteToProfileViewAction";

export default class RouteToProfileViewAction extends AbstractRouteToProfileViewAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



