/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToForgotPasswordAction from "../../../gen/common/actions/AbstractRouteToForgotPasswordAction";

export default class RouteToForgotPasswordAction extends AbstractRouteToForgotPasswordAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



