/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToBoxCreateAction from "../../../gen/common/actions/AbstractRouteToBoxCreateAction";

export default class RouteToBoxCreateAction extends AbstractRouteToBoxCreateAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



