/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import React from "react";


export const Modal = (props) => {
    return <div className="modal">
        <div className="modalContent">
            <h2>{props.title}</h2>
            <div className="message">{props.message}</div>
            <button
                className="yes danger"
                onClick={props.onConfirm}
            >
                {props.confirm}
            </button>
            <button
                onClick={props.onCancel}
            >
                {props.cancel}
            </button>
        </div>
    </div>
}


/******* S.D.G. *******/



