/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteUserCancelAction from "../../../gen/profile/actions/AbstractDeleteUserCancelAction";

export default class DeleteUserCancelAction extends AbstractDeleteUserCancelAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



