/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {ExpandedCategoryItem} from "../../../../../../common/ExpandedCategoryItem";

export const RootCategoryInMoveDialog = (props) => {
	return <div className="categoryTreeItems">
		<div className="categoryItem depth_1">
			<ExpandedCategoryItem {...props}/>
			<div>
				{props.children}
			</div>
		</div>
	</div>
}



/******* S.D.G. *******/



