/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const Buttons = (props) => {
	return <div>
		{props.children}
	</div>
}



/******* S.D.G. *******/



