/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const CardView = (props) => {
	if (!props.rootCategory || !props.cardTable || !props.cardTable.cardList || !props.selectedCategory) {
		return null;
	}

	const dictionary = () => {
		if (!props.rootCategory.givenLanguage || !props.rootCategory.wantedLanguage) {
			return null;
		}
		const setFocus = () => {
			document.getElementById(props.naturalInputOrder === true ? "wanted" : "given").focus();
		}

		const value = props.dictionaryValue;

		if (!value || value.length === 0) {
			return <div className="iframePlaceholder"/>
		}

		const languageMap = {
			"de": "deutsch",
			"fr": "franzoesisch",
			"en": "englisch"
		};
		const sourceLanguage = props.naturalInputOrder === true ? props.rootCategory.givenLanguage : props.rootCategory.wantedLanguage;
		const targetLanguage = props.naturalInputOrder === true ? props.rootCategory.wantedLanguage : props.rootCategory.givenLanguage;

		const src = `https://www.linguee.de/${languageMap[sourceLanguage]}-${languageMap[targetLanguage]}/search?query=${value}`;
		return <div className="dictionaryWrapper">
			<iframe
				src={src}
				frameBorder={0}
				onLoad={setFocus}
				sandbox="allow-scripts"
			/>
		</div>
	}

	return <div>
		<h1>
			{props.selectedCategory.categoryName}
			{props.reverse === true ? <i className="fas fa-arrows-alt-h"/> : null}
		</h1>
		{props.children}
		{dictionary()}
	</div>
}



/******* S.D.G. *******/



