/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../../../app/Texts";
import {
	cancelCategoryDialog,
	categoryNameChanged,
	createCategory,
	updateCategory
} from "../../../../../../gen/category/ActionFunctions";
import {translate} from "../../../../../AppUtils";


export const CategoryDialog = (props) => {
    if (props.display !== true) {
		return null;
	}
	const disabled =
		!props.categoryName ||
		props.categoryName.length === 0;

	return <div className="modal">
		<div className="modalContent form">
			<h2>{props.newCategory ? translate(Texts.categoryTree.newCategory.title) : translate(Texts.categoryTree.editCategory.title)}</h2>
			<div className="line">
				<input
					type="text"
					onChange={(event) => categoryNameChanged(event.target.value)}
					autoComplete="off"
					value={props.categoryName}
					placeholder={translate(Texts.categoryTree.newCategory.newChildCategory)}
					id="categoryName"
				/>
			</div>
			<button
				disabled={disabled}
				onClick={() => props.newCategory ? createCategory() : updateCategory()}
				id="ok"
			>
				{translate(Texts.categoryTree.newCategory.ok)}
			</button>
			<button
				onClick={cancelCategoryDialog}
			>
				{translate(Texts.categoryTree.newCategory.cancel)}
			</button>
		</div>
	</div>;
}



/******* S.D.G. *******/



