/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const CategoryDialog = (props) => {
	return <>
		<div>categoryName: {props.categoryName !== null && props.categoryName !== undefined ? props.categoryName.toString() : ""}</div>
		<div>newCategory: {props.newCategory !== null && props.newCategory !== undefined ? props.newCategory.toString() : ""}</div>
		<div>display: {props.display !== null && props.display !== undefined ? props.display.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



