/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const DeleteCategoryDialog = (props) => {
	return <>
		<h1>DeleteCategoryDialog</h1>
		<ul>
			<li>display: {props.display !== null && props.display !== undefined ? props.display.toString() : ""}</li>
		</ul>
	</> 
}



/******* S.D.G. *******/



