/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const DeleteCategoryDialog = (props) => {
	return <>
		<div>display: {props.display !== null && props.display !== undefined ? props.display.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



