/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../AppUtils";
import {Texts} from "../../../../../app/Texts";

export const DeleteCategoryDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{translate(Texts.categoryTree.confirmDelete.title)}</h2>
				<div className="message">{translate(Texts.categoryTree.confirmDelete.message)}</div>
				<button
					className="yes danger"
					onClick={props.deleteCategory}
				>
					{translate(Texts.categoryTree.confirmDelete.ok)}
				</button>
				<button
					onClick={props.cancelDeleteCategory}
				>
					{translate(Texts.categoryTree.confirmDelete.cancel)}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



