/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const InviteUserEditableDialog = (props) => {
	return <>
		<div>invitedUsername: {props.invitedUsername !== null && props.invitedUsername !== undefined ? props.invitedUsername.toString() : ""}</div>
		<div>editable: {props.editable !== null && props.editable !== undefined ? props.editable.toString() : ""}</div>
		<div>display: {props.display !== null && props.display !== undefined ? props.display.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



