/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {cancelInviteUser, inviteUser, inviteUserChangeEditable} from "../../../../../../gen/category/ActionFunctions";
import {Texts} from "../../../../../app/Texts";


export const InviteUserEditableDialog = (props) => {
    if (props.display !== true) {
        return null;
    }
    return <div className="modal">
        <div className="modalContent form">
            <h2>{Texts.categoryTree.inviteUser.title[props.language]}</h2>
            <div className="line">
                {props.invitedUsername}
            </div>
            <div className="line">
                <input
                    type="checkbox"
                    onChange={inviteUserChangeEditable}
                    checked={props.editable}
                    id="editable"
                />
                <label
                    htmlFor="editable"
                >
                    {Texts.categoryTree.inviteUser.editable[props.language]}
                </label>
            </div>
            <button onClick={inviteUser}>{Texts.categoryTree.inviteUser.invite[props.language]}</button>
            <button onClick={cancelInviteUser}>{Texts.categoryTree.inviteUser.cancel[props.language]}</button>
        </div>
    </div>
}


/******* S.D.G. *******/



