/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const RootCategory = (props) => {
	return <>
		<div>categoryId: {props.categoryId !== null && props.categoryId !== undefined ? props.categoryId.toString() : ""}</div>
		<div>categoryName: {props.categoryName !== null && props.categoryName !== undefined ? props.categoryName.toString() : ""}</div>
		<div>categoryIndex: {props.categoryIndex !== null && props.categoryIndex !== undefined ? props.categoryIndex.toString() : ""}</div>
		<div>empty: {props.empty !== null && props.empty !== undefined ? props.empty.toString() : ""}</div>
		<div>parentCategoryId: {props.parentCategoryId !== null && props.parentCategoryId !== undefined ? props.parentCategoryId.toString() : ""}</div>
		<div>dictionaryLookup: {props.dictionaryLookup !== null && props.dictionaryLookup !== undefined ? props.dictionaryLookup.toString() : ""}</div>
		<div>givenLanguage: {props.givenLanguage !== null && props.givenLanguage !== undefined ? props.givenLanguage.toString() : ""}</div>
		<div>wantedLanguage: {props.wantedLanguage !== null && props.wantedLanguage !== undefined ? props.wantedLanguage.toString() : ""}</div>
		<div>rootCategoryId: {props.rootCategoryId !== null && props.rootCategoryId !== undefined ? props.rootCategoryId.toString() : ""}</div>
		<div>nonScheduledCount: {props.nonScheduledCount !== null && props.nonScheduledCount !== undefined ? props.nonScheduledCount.toString() : ""}</div>
		<div>editable: {props.editable !== null && props.editable !== undefined ? props.editable.toString() : ""}</div>
		<div>childCategories: {props.childCategories !== null && props.childCategories !== undefined ? props.childCategories.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



