/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

import { passwordRepetitionChanged } from "../../../../../gen/password/ActionFunctions";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";
import CryptoJS from "crypto-js";

export const PasswordRepetition = (props) => {
	return <div className="line">
		<label>{translate(Texts.resetPassword.passwordRepetition)}</label>
		<div className="inputContainer">
			<input
				type={"password"}
				onChange={(e) => passwordRepetitionChanged(CryptoJS.MD5(e.target.value).toString())}
				autoComplete="off"
			/>
			{props.passwordMismatch === true &&
			<i className="fas fa-times outside error"/>}
		</div>
	</div>
}



/******* S.D.G. *******/



