/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

import { passwordChanged } from "../../../../../gen/password/ActionFunctions";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";
import CryptoJS from "crypto-js";

export const Password = (props) => {
	return <div className="line">
		<label>{translate(Texts.resetPassword.password)}</label>
		<div className="inputContainer">
			<input
				type={"password"}
				onChange={(e) => passwordChanged(CryptoJS.MD5(e.target.value).toString())}
				autoComplete="off"
			/>
		</div>
	</div>
}



/******* S.D.G. *******/



