/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadUserCommand from "../../../gen/profile/commands/AbstractLoadUserCommand";

export default class LoadUserCommand extends AbstractLoadUserCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.profileView = {
            username: {
                value: data.username
            },
            email: {
                value: data.email
            },
            role: data.role,
            showDeleteUserDialog: false,
            deletable: data.deletable
        };
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



