/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




const {assertMessage} = require("../registrationscenarios/Utils");
module.exports = {
	errorWasHidden: async function(actual) {
		return assertMessage(actual[0], {type: "error", id: 0, visible: false})
	}
}



/******* S.D.G. *******/


