/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




const {assertMessage} = require("../registrationscenarios/Utils");
module.exports = {
    confirmEmailErrorMessageShown: async function (actual) {
        return assertMessage(actual[0], {
            type: "info",
            id: 0,
            visible: true
        }) && assertMessage(actual[1], {type: "error", id: 1, visible: true})
    }
}


/******* S.D.G. *******/


