/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/


const ScenarioUtils = require("../ScenarioUtils");


module.exports = {
	loginDataWasNotSetInLocalStorage: async function(driver, testId) {
		expect(await ScenarioUtils.getValueFromLocalStorage(driver, "token")).toBeNull();
	}
}



/******* S.D.G. *******/


