/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




const {registerDisabled, registerEnabled} = require("./Utils");
module.exports = {
	registerDisabled: registerDisabled,
	registerEnabled: registerEnabled,
}



/******* S.D.G. *******/


