/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/



const {registerDisabled, registerEnabled} = require("./Utils");
const ScenarioUtils = require("../ScenarioUtils");

module.exports = {
	registerDisabled: registerDisabled,
	registerEnabled: registerEnabled,
	loginDataWasNotSetInLocalStorage: async function(driver, testId) {
		return await ScenarioUtils.getValueFromLocalStorage(driver, "token") === null
	}
}



/******* S.D.G. *******/


