/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




const {until, By} = require("selenium-webdriver");
module.exports = {
	okDisabled: async function(driver, testId) {
		await driver.wait(until.elementLocated(By.id('ok')), 5000);
		return await driver.findElement(By.id("ok")).isEnabled() === false
	}
}



/******* S.D.G. *******/


