/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const ChildCategoriesItem = (props) => {
	const json = JSON.stringify(props, null, '\t');
	return <div>
		<div>{props.categoryId}</div>
		<div>{props.categoryName}</div>
		<div>{props.categoryIndex}</div>
		<div>{props.empty}</div>
		<div>{props.parentCategoryId}</div>
		<div>{props.dictionaryLookup}</div>
		<div>{props.givenLanguage}</div>
		<div>{props.wantedLanguage}</div>
		<div>{props.rootCategoryId}</div>
		<div>{props.nonScheduledCount}</div>
		<div>{props.editable}</div>
		<pre>{json}</pre>
	</div> 
}



/******* S.D.G. *******/



