/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const ChildCategoriesItem = (props) => {
	return <>
		<h1>ChildCategoriesItem</h1>
		<ul>
			<li>categoryId: {props.categoryId !== null && props.categoryId !== undefined ? props.categoryId.toString() : ""}</li>
			<li>categoryName: {props.categoryName !== null && props.categoryName !== undefined ? props.categoryName.toString() : ""}</li>
			<li>categoryIndex: {props.categoryIndex !== null && props.categoryIndex !== undefined ? props.categoryIndex.toString() : ""}</li>
			<li>empty: {props.empty !== null && props.empty !== undefined ? props.empty.toString() : ""}</li>
			<li>parentCategoryId: {props.parentCategoryId !== null && props.parentCategoryId !== undefined ? props.parentCategoryId.toString() : ""}</li>
			<li>dictionaryLookup: {props.dictionaryLookup !== null && props.dictionaryLookup !== undefined ? props.dictionaryLookup.toString() : ""}</li>
			<li>givenLanguage: {props.givenLanguage !== null && props.givenLanguage !== undefined ? props.givenLanguage.toString() : ""}</li>
			<li>wantedLanguage: {props.wantedLanguage !== null && props.wantedLanguage !== undefined ? props.wantedLanguage.toString() : ""}</li>
			<li>rootCategoryId: {props.rootCategoryId !== null && props.rootCategoryId !== undefined ? props.rootCategoryId.toString() : ""}</li>
			<li>nonScheduledCount: {props.nonScheduledCount !== null && props.nonScheduledCount !== undefined ? props.nonScheduledCount.toString() : ""}</li>
			<li>editable: {props.editable !== null && props.editable !== undefined ? props.editable.toString() : ""}</li>
		</ul>
		{props.children}
	</> 
}



/******* S.D.G. *******/



