/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {route} from "../../../../../../../gen/common/ActionFunctions";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const Back = (props) => {
    return <button
        onClick={props.onClick}
        title={translate(Texts.categoryTree.back)}
    >
        <i className="fa fa-arrow-left"/>
    </button>
}


/******* S.D.G. *******/



