/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const Delete = (props) => {
	if (props.rootCategory && props.rootCategory.editable) {
		return <button
			disabled={
				!props.selectedCategory ||
				props.selectedCategory.empty === false ||
				props.rootCategory.categoryId === props.selectedCategory.categoryId
			}
			onClick={props.onClick}
			title={translate(Texts.categoryTree.delete)}
		>
			<i className="far fa-trash-alt"/>
		</button>
	}
	return null
}



/******* S.D.G. *******/



