/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const Invite = (props) => {
	if (props.rootCategory && props.rootCategory.editable) {
		return <button
			disabled={!props.selectedCategory}
			onClick={props.onClick}
			title={translate(Texts.categoryTree.inviteUser.title)}
		>
			<i className="fas fa-share"/>
		</button>
	}
	return null
}



/******* S.D.G. *******/



