/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const Move = (props) => {
	return <button
		disabled={props.selectedCategory && props.selectedCategory.categoryId === props.rootCategory.categoryId}
		onClick={props.onClick}
		title={translate(Texts.categoryTree.moveCategory.title)}
		id="new"
	>
		<i className="fas fa-arrows-alt"></i>
	</button>
}



/******* S.D.G. *******/



