/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const New = (props) => {
	if (props.rootCategory && props.rootCategory.editable) {
		return <button
			disabled={!props.selectedCategory}
			onClick={props.onClick}
			title={translate(Texts.categoryTree.newCategory.newChildCategory)}
			id="new"
		>
			<i className="fas fa-plus"/>
		</button>
	}
	return null;
}



/******* S.D.G. *******/



