/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const Reverse = (props) => {
	if (props.reverseBoxExists === false) {
		return <button
			onClick={props.onClick}
			title={translate(Texts.categoryTree.createReverseBox)}
		>
			<i className="far fa-clone"/>
		</button>
	}
	return null
}


/******* S.D.G. *******/



