/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const ToggleOrderUp = (props) => {
    return <button
        onClick={() => props.onClick(false)}
        title={translate(Texts.categoryTree.moveUp)}
    >
        <i className="fas fa-angle-up"></i>
    </button>
}


/******* S.D.G. *******/



