/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const ToggleOrderDown = (props) => {
	return <button
		onClick={() => props.onClick(true)}
		title={translate(Texts.categoryTree.moveDown)}
	>
		<i className="fas fa-angle-down"></i>
	</button>
}



/******* S.D.G. *******/



