/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../../../../AppUtils";
import {Texts} from "../../../../../../../../../app/Texts";

export const MoveCards = (props) => {
	return <button
		onClick={props.onClick}
		title={translate(Texts.cardList.moveSelectedCardsToSelectedCategory)}
		disabled={props.selectedCardIds.length === 0}
	>
		<i className="fas fa-arrows-alt"></i>
	</button>
}



/******* S.D.G. *******/



