/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import AbstractLoginCommand from "../../../gen/login/commands/AbstractLoginCommand";
import {Texts} from "../../app/Texts";

export default class LoginCommand extends AbstractLoginCommand {

    validateCommandData() {
        return true;
    }

    handleResponse(data, resolve) {
        if (data.saveInLocalStorage === true) {
            this.addSaveInLocalStorageOutcome(data);
        }
        this.addOkOutcome(data);
        resolve(data);
    }

    handleError(data, resolve) {
        data.textKey = Texts.messages.loginFailed;
        this.addUnauthorizedOutcome(data);
        data.password = {
            value: ""
        };
        resolve(data);
    }
}


/******* S.D.G. *******/



