/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../../../app/Texts";
import {cancelDeleteCategory, deleteCategory} from "../../../../../../gen/category/ActionFunctions";
import {translate} from "../../../../../AppUtils";


export const DeleteCategoryDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{translate(Texts.categoryTree.confirmDelete.title)}</h2>
				<div className="message">{translate(Texts.categoryTree.confirmDelete.message)}</div>
				<button
					className="yes danger"
					onClick={deleteCategory}
				>
					{translate(Texts.categoryTree.confirmDelete.ok)}
				</button>
				<button
					onClick={cancelDeleteCategory}
				>
					{translate(Texts.categoryTree.confirmDelete.cancel)}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



