/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




const {saveDisabled} = require("./Utils");
module.exports = {
	saveDisabled: saveDisabled,
}



/******* S.D.G. *******/


