/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




const {
    saveDisabled,
    saveEnabled,
    givenLanguageDisabled,
    wantedLanguageDisabled,
    givenLanguageEnabled,
	wantedLanguageEnabled
} = require("./Utils");
module.exports = {
    saveEnabled: saveEnabled,
    givenLanguageEnabled: givenLanguageEnabled,
	wantedLanguageEnabled: wantedLanguageEnabled,
    saveDisabled: saveDisabled,
    givenLanguageDisabled: givenLanguageDisabled,
    wantedLanguageDisabled: wantedLanguageDisabled,
}


/******* S.D.G. *******/


