/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




const {
	saveEnabled,
	saveDisabled,
	givenLanguageDisabled,
	wantedLanguageDisabled
} = require("./Utils");
module.exports = {
	saveEnabled: saveEnabled,
	saveDisabled: saveDisabled,
	givenLanguageDisabled: givenLanguageDisabled,
	wantedLanguageDisabled: wantedLanguageDisabled,
}



/******* S.D.G. *******/


