/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/


const {saveDisabled, givenLanguageDisabled, wantedLanguageDisabled} = require("./Utils");


module.exports = {
	saveDisabled: saveDisabled,
	givenLanguageDisabled: givenLanguageDisabled,
	wantedLanguageDisabled: wantedLanguageDisabled,
}



/******* S.D.G. *******/


