/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {route} from "../../../../../../gen/common/ActionFunctions";
import {translate} from "../../../../../AppUtils";
import {Texts} from "../../../../../app/Texts";

export const Cancel = () => {
    return <button
        onClick={() => route("#")}>{translate(Texts.forgotPassword.cancel)}
    </button>

}


/******* S.D.G. *******/



