/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {translate} from "../../../../../AppUtils";
import {Texts} from "../../../../../app/Texts";

export const Cancel = (props) => {
    return <button onClick={props.onClick}>
        {translate(Texts.forgotPassword.cancel)}
    </button>

}


/******* S.D.G. *******/



