/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {forgotPassword} from "../../../../../../gen/password/ActionFunctions";
import {translate} from "../../../../../AppUtils";
import {Texts} from "../../../../../app/Texts";

export const ForgotPassword = (props) => {
    return <button onClick={forgotPassword}
                   disabled={props.disabled}>
        {translate(Texts.forgotPassword.submit)}
    </button>
}


/******* S.D.G. *******/



