/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";

import { CategoryTree } from "./authorView/CategoryTree";
import { CardView } from "./authorView/CardView";

export const AuthorView = (props) => {
	return <div className="categoryCardSplitView">
		<CategoryTree {...props.categoryTree} />
		<CardView {...props.cardView} categoryTree={props.categoryTree}/>
	</div>
}



/******* S.D.G. *******/



