/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPasswordChangedAction from "../../../gen/registration/actions/AbstractPasswordChangedAction";

export default class PasswordChangedAction extends AbstractPasswordChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



