/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractValidateAction from "../../../gen/registration/actions/AbstractValidateAction";

export default class ValidateAction extends AbstractValidateAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



