/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractFilterNonScheduledCardsAction from "../../../gen/category/actions/AbstractFilterNonScheduledCardsAction";

export default class FilterNonScheduledCardsAction extends AbstractFilterNonScheduledCardsAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



