/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetInvitedUsernamesAction from "../../../gen/category/actions/AbstractGetInvitedUsernamesAction";

export default class GetInvitedUsernamesAction extends AbstractGetInvitedUsernamesAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



