/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractInviteUserChangeEditableAction from "../../../gen/category/actions/AbstractInviteUserChangeEditableAction";

export default class InviteUserChangeEditableAction extends AbstractInviteUserChangeEditableAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



