/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractInviteUserNextStepAction from "../../../gen/category/actions/AbstractInviteUserNextStepAction";

export default class InviteUserNextStepAction extends AbstractInviteUserNextStepAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



