/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractItemDroppedAction from "../../../gen/category/actions/AbstractItemDroppedAction";

export default class ItemDroppedAction extends AbstractItemDroppedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



