/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadCategoryTreeAction from "../../../gen/category/actions/AbstractLoadCategoryTreeAction";

export default class LoadCategoryTreeAction extends AbstractLoadCategoryTreeAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



