/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCategoryCancelledAction from "../../../gen/category/actions/AbstractMoveCategoryCancelledAction";

export default class MoveCategoryCancelledAction extends AbstractMoveCategoryCancelledAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



