/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCategoryAllowedAction from "../../../gen/category/actions/AbstractMoveCategoryAllowedAction";

export default class MoveCategoryAllowedAction extends AbstractMoveCategoryAllowedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



