/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCategoryClickedAction from "../../../gen/category/actions/AbstractMoveCategoryClickedAction";

export default class MoveCategoryClickedAction extends AbstractMoveCategoryClickedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



