/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractToggleCategoryOrderAction from "../../../gen/category/actions/AbstractToggleCategoryOrderAction";

export default class ToggleCategoryOrderAction extends AbstractToggleCategoryOrderAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



