/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../AppUtils";

export const MessagesItem = (props) => {
	const text = translate(props.textKey, props.args);
	return <div
		className={`${props.visible === false ? "fadeOut" : ""}`}
		onClick={() => props.destroyToast(props.id)}
	>
		<div id={`toast_${props.id}`} className={`toast ${props.type}`}>{text}</div>
	</div>
}



/******* S.D.G. *******/



