/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const Archive = (props) => {
	return <button
		boxId={props.boxId}
		archived={props.archived}
		className="button"
		onClick={(event) => props.onClick(props.archived,props.boxId)}
	>
		archive
	</button>
}



/******* S.D.G. *******/



