/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

const cardsNextDaysItem = (item) => {
    const toDoFactor = item.count * 1.0 / item.maxCardsPerDay;
    return <div
        key={item.index}
        className={`${item.rounded} cards-next-days-item`}
        style={{background: `rgba(192, 192, 192, ${toDoFactor})`}}
    >
        {item.count}
    </div>
}
export const CardsNextDays = (props) => {
    if (props.archived === true) {
        return null;
    }

    const onClick = (e) => {
        e.stopPropagation();
        props.onClick(props.boxId)
    }
    if (props.countsPerDayNextWeek && props.countsPerDayNextWeek.length === 7 && props.maxCardsPerDay && props.maxCardsPerDay > 0) {
        let index = 0;
        let items = props.countsPerDayNextWeek.map((count) => {
            index++;
            return cardsNextDaysItem({
                maxCardsPerDay: props.maxCardsPerDay,
                count,
                index,
                language: props.language,
                rounded: index === 1 ? "rounded-left" : index === 7 ? "rounded-right" : ""
            });
        });
        return <div>
            <br/>
            <div
                className="cards-next-days"
                onClick={(e) => onClick(e)}
            >
                {items}
            </div>
        </div>
    }
    return null;
}


/******* S.D.G. *******/



