/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const Delete = (props) => {
	return <button 
		boxId={props.boxId}
		deletable={props.deletable}
		className="button"
		onClick={(event) => props.onClick(props.boxId)}
	>
		delete
	</button>
}



/******* S.D.G. *******/



