/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const Edit = (props) => {
	return <button 
		categoryId={props.categoryId}
		reverse={props.reverse}
		className="button"
		onClick={(event) => props.onClick(props.categoryId,props.reverse)}
	>
		edit
	</button>
}



/******* S.D.G. *******/



