/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import "./style.scss";
import "./root.scss";


export const RootContainer = (props) => {
	return <div className={"root"}>
		{props.children}
	</div>
}



/******* S.D.G. *******/



