/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const RootContainer = (props) => {
	return <div id="rootContainer" className={props.loggedInUser? "wrapper" : ""}>
		{props.children}
	</div>
}



/******* S.D.G. *******/



