/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




module.exports = {
	registerDisabled: async function(driver, testId) {
		fail("registerDisabled not implemented");
	}
}



/******* S.D.G. *******/


