/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractConfirmEmailCommand from "../../../gen/registration/commands/AbstractConfirmEmailCommand";
import * as AppUtils from "../../AppUtils";

export default class ConfirmEmailCommand extends AbstractConfirmEmailCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.hash = "#";
        data.message = AppUtils.createInfoMessage("emailConfirmed");
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve) {
        data.hash = "#";
        data.message = AppUtils.createError("emailNotConfirmed");
        this.addErrorOutcome(data);
        resolve(data);
    }
}




/******* S.D.G. *******/



