/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractConfirmEmailCommand from "../../../gen/registration/commands/AbstractConfirmEmailCommand";
import {Texts} from "../../app/Texts";

export default class ConfirmEmailCommand extends AbstractConfirmEmailCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.textKey = Texts.messages.emailConfirmed;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve) {
        data.textKey = Texts.messages.emailNotConfirmed;
        this.addErrorOutcome(data);
        resolve(data);
    }
}




/******* S.D.G. *******/



