/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoginCommand from "../../../gen/registration/commands/AbstractLoginCommand";

export default class LoginCommand extends AbstractLoginCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



