/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const CardDuplicatesItem = (props) => {
	const renderGiven = () => {
		return <td>
			<pre>{props.given}</pre>
		</td>
	}

	const renderWanted = () => {
		return <td>
			<pre>{props.wanted}</pre>
		</td>
	}
	const renderPath = () => {
		return <td colSpan={2}>
			<a onClick={() => props.routeToSelectedCategory(props.rootCategory.rootCategoryId, props.categoryId)}>
				{props.categoryName}
			</a>
		</td>
	}

	return <tr className="notPrinted">
		<td/>
		{props.naturalInputOrder === true ? renderGiven() : renderWanted()}
		{props.naturalInputOrder === true ? renderWanted() : renderGiven()}
		{renderPath()}
	</tr>
}



/******* S.D.G. *******/



