/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {CardEditMode} from "./CardEditMode";
import {CardReadonly} from "./CardReadonly";

export const CardListItem = (props) => {
    if (!(props.given.indexOf(props.filter) >= 0 || props.wanted.indexOf(props.filter) >= 0)) {
        return null;
    }
    const editable = props.rootCategory.editable;
    const editMode = props.cardId === props.editedCard.cardId && editable;

    if (editMode && editMode) {
        return <CardEditMode {...props} editable={editable}/>
    }
    return <CardReadonly {...props} editable={editable}/>
}



/******* S.D.G. *******/



