/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../../../../../AppUtils";
import {Texts} from "../../../../../../../app/Texts";
import {CardInput} from "./CardInput";
import {CardPreview} from "./CardPreview";

export const CardReadonly = (props) => {
    if (!(props.given.indexOf(props.filter) >= 0 || props.wanted.indexOf(props.filter) >= 0)) {
        return null;
    }

    const onCheckboxClicked = (e) => {
        if (e.nativeEvent.shiftKey === true) {
            props.selectScheduleCardRange(props.cardId)
        } else {
            props.toggleScheduleCardSelection(props.cardId)
        }
    }

    const renderGiven = () => {
        return CardPreview({
            text: props.given,
            onEdit: () => props.editable ? props.editCard(props.cardId) : {}
        })
    }

    const renderWanted = () => {
        return CardPreview({
            text: props.wanted,
            onEdit: () => props.editable ? props.editCard(props.cardId) : {}
        })
    }

    const priority = () => {
        const priorityChanged = (priority) => {
            if (props.editable) {
                props.updateCardPriority(props.cardId, priority).then();
            }
        }
        const priorityClass = (index) => {
            if (props.priority && index <= props.priority) {
                return "fa fa-star";
            }
            return "far fa-star";
        }
        return <div className="priority noBreak">
            <i
                className={priorityClass(1)}
                onClick={
                    props.editable ?
                        () => priorityChanged(props.priority === 1 ? null : 1) :
                        () => {
                        }
                }
            />
            <i
                className={priorityClass(2)}
                onClick={
                    props.editable ?
                        () => priorityChanged(props.priority === 2 ? null : 2) :
                        () => {
                        }
                }
            />
            <i
                className={priorityClass(3)}
                onClick={
                    props.editable ?
                        () => priorityChanged(props.priority === 3 ? null : 3) :
                        () => {
                        }
                }
            />
        </div>
    }

    return <div className="cardListItem readonly">
        <input
            type="checkbox"
            onChange={onCheckboxClicked}
            checked={props.selectedCardIds.indexOf(props.cardId) >= 0}
        />
        <div className="givenAndWanted">
            {props.naturalInputOrder === true ? renderGiven() : renderWanted()}
            {props.naturalInputOrder === true ? renderWanted() : renderGiven()}
        </div>
        {priority()}
        <div className="schedule">
            {props.next ?
                <i className="far fa-calendar-check" title={new Date(props.next).toLocaleDateString()}></i> : ""}
        </div>
    </div>
}


/******* S.D.G. *******/



