/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {CardPreview} from "./CardPreview";

export const CardDuplicatesItem = (props) => {
	const renderGiven = () => {
		return CardPreview({text: props.given})
	}

	const renderWanted = () => {
		return CardPreview({text: props.wanted})
	}
	const renderPath = () => {
		return <td colSpan={2}>
			<a onClick={() => props.routeToSelectedCategory(props.rootCategory.rootCategoryId, props.categoryId, props.reverse)}>
				{props.categoryName}
			</a>
		</td>
	}

	return <tr className="notPrinted">
		<td/>
		{props.naturalInputOrder === true ? renderGiven() : renderWanted()}
		{props.naturalInputOrder === true ? renderWanted() : renderGiven()}
		{renderPath()}
	</tr>
}



/******* S.D.G. *******/



