/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {logout, route, routeToProfileView} from "../../../gen/common/ActionFunctions";
import {translate} from "../../AppUtils";
import {Texts} from "../../app/Texts";


export const LoggedInUser = (props) => {
    if (props.username) {
        return <div className="header">
            <a
                onClick={() => route("#dashboard")}
                className="title"
            >
                Anfelisa
            </a>
            <div className="logout">
                <a id="profile" onClick={() => routeToProfileView()}>{props.username}</a>
                <button id="logout" onClick={logout}>{translate(Texts.logout.signout)}</button>
            </div>
        </div>
    }
    return null;
}


/******* S.D.G. *******/



