/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {logout, route} from "../../../gen/common/ActionFunctions";
import {Texts} from "../../app/Texts";


export const LoggedInUser = (props) => {
	if (props.username) {
		return <div className="logout">
			<a id="profile" onClick={() => route("#profile")}>{props.username}</a>
			<button id="logout" onClick={logout}>{Texts.logout.signout[props.language]}</button>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



