/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../AppUtils";
import {Texts} from "../../app/Texts";
import "./loggedInUser.scss"


export const LoggedInUser = (props) => {
    return <div className={`header ${props.username ? 'wide-header' : 'center-header'}`}>
        <a
            onClick={props.routeToDefault}
            className="title"
        >
            Anfelisa
        </a>
        {props.username && <div className="profile">
            <a className="username" onClick={props.routeToProfileView}>{props.username}</a>
            <button className="logout primary" onClick={props.logout}>{translate(Texts.logout.signout)}</button>
        </div>}
    </div>
}


/******* S.D.G. *******/



