/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";

import { PrivacyPolicyView } from "./mainView/PrivacyPolicyView";
import { LoginView } from "./mainView/LoginView";
import { RegistrationView } from "./mainView/RegistrationView";
import { ForgotPasswordView } from "./mainView/ForgotPasswordView";
import { ResetPasswordView } from "./mainView/ResetPasswordView";
import { DashboardView } from "./mainView/DashboardView";
import { BoxSettingsView } from "./mainView/BoxSettingsView";
import { AllActiveCardsView } from "./mainView/AllActiveCardsView";
import { ProfileView } from "./mainView/ProfileView";
import { QueryCardView } from "./mainView/QueryCardView";
import { AuthorView } from "./mainView/AuthorView";

export const MainView = (props) => {
	if (props.group === "privacyPolicyView") {
		return <PrivacyPolicyView {...props}/>;
	}
	if (props.group === "loginView") {
		return <LoginView {...props}/>;
	}
	if (props.group === "registrationView") {
		return <RegistrationView {...props}/>;
	}
	if (props.group === "forgotPasswordView") {
		return <ForgotPasswordView {...props}/>;
	}
	if (props.group === "resetPasswordView") {
		return <ResetPasswordView {...props}/>;
	}
	if (props.group === "dashboardView") {
		return <DashboardView {...props}/>;
	}
	if (props.group === "boxSettingsView") {
		return <BoxSettingsView {...props}/>;
	}
	if (props.group === "allActiveCardsView") {
		return <AllActiveCardsView {...props}/>;
	}
	if (props.group === "profileView") {
		return <ProfileView {...props}/>;
	}
	if (props.group === "queryCardView") {
		return <QueryCardView {...props}/>;
	}
	if (props.group === "authorView") {
		return <AuthorView {...props}/>;
	}
	return null;
}



/******* S.D.G. *******/



