/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";

import { PrivacyPolicyView } from "./mainView/PrivacyPolicyView";
import { LoginView } from "./mainView/LoginView";
import { RegistrationView } from "./mainView/RegistrationView";
import { ForgotPasswordView } from "./mainView/ForgotPasswordView";
import { ResetPasswordView } from "./mainView/ResetPasswordView";
import { DashboardView } from "./mainView/DashboardView";
import { BoxSettingsView } from "./mainView/BoxSettingsView";
import { AllActiveCardsView } from "./mainView/AllActiveCardsView";
import { ProfileView } from "./mainView/ProfileView";
import { QueryCardView } from "./mainView/QueryCardView";
import { AuthorView } from "./mainView/AuthorView";

export const MainView = (props) => {
	if (props.privacyPolicyView) {
		return <PrivacyPolicyView {...props.privacyPolicyView} {...props.loggedInUser}/>;
	}
	if (props.loginView) {
		return <LoginView {...props.loginView} {...props.loggedInUser}/>;
	}
	if (props.registrationView) {
		return <RegistrationView {...props.registrationView} {...props.loggedInUser}/>;
	}
	if (props.forgotPasswordView) {
		return <ForgotPasswordView {...props.forgotPasswordView} {...props.loggedInUser}/>;
	}
	if (props.resetPasswordView) {
		return <ResetPasswordView {...props.resetPasswordView} {...props.loggedInUser}/>;
	}
	if (props.dashboardView) {
		return <DashboardView {...props.dashboardView} {...props.loggedInUser}/>;
	}
	if (props.boxSettingsView) {
		return <BoxSettingsView {...props.boxSettingsView} {...props.loggedInUser}/>;
	}
	if (props.allActiveCardsView) {
		return <AllActiveCardsView {...props.allActiveCardsView} {...props.loggedInUser}/>;
	}
	if (props.profileView) {
		return <ProfileView {...props.profileView} {...props.loggedInUser}/>;
	}
	if (props.queryCardView) {
		return <QueryCardView {...props.queryCardView} {...props.loggedInUser}/>;
	}
	if (props.authorView) {
		return <AuthorView {...props.authorView} {...props.loggedInUser}/>;
	}
	return null;
}



/******* S.D.G. *******/



