/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import "./mainView.scss"


export const MainView = (props) => {
	return <div className="mainView">
		{props.children}
	</div>
}



/******* S.D.G. *******/



