/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const MessageContainer = (props) => {
	return <div className="toastContainer">
		{props.children}
	</div>
}



/******* S.D.G. *******/



