/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../AppUtils";
import {Texts} from "../../app/Texts";
import {Modal} from "../common/Modal";


export const SaveBugDialog = (props) => {
    if (props.display === true) {
        return <Modal
            title={translate(Texts.container.unexpectedBug)}
            message={translate(Texts.container.unexpectedBugMessage)}
            confirm={translate(Texts.container.yes)}
            cancel={translate(Texts.container.no)}
            onConfirm={props.callSaveBug}
            onCancel={props.cancelSaveBugDialog}
        />
    }
    return null;
}


/******* S.D.G. *******/



