/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../AppUtils";
import {Texts} from "../../app/Texts";
import {cancelVersionMismatchDialog} from "../../../gen/common/ActionFunctions";


export const VersionMismatchDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{translate(Texts.container.versionMismatch)}</h2>
				<div className="message">{translate(Texts.container.versionMismatchMessage)}</div>
				<button
					className="yes"
					onClick={() => window.location.reload(true)}
				>
					{translate(Texts.container.yes)}
				</button>
				<button
					onClick={() => cancelVersionMismatchDialog()}
				>
					{translate(Texts.container.no)}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



