/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../AppUtils";
import {Texts} from "../../app/Texts";


export const VersionMismatchErrorDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent danger">
				<h2>{translate(Texts.container.versionMismatchError)}</h2>
				<div className="message">{translate(Texts.container.versionMismatchErrorMessage)}</div>
				<button
					className="yes"
					onClick={() => window.location.reload(true)}
				>
					{translate(Texts.container.ok)}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



