/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../AppUtils";
import {Texts} from "../../app/Texts";
import {Modal} from "../common/Modal";


export const VersionMismatchDialog = (props) => {
	if (props.display === true) {
		return <Modal
			title={translate(Texts.container.versionMismatch)}
			message={translate(Texts.container.versionMismatchMessage)}
			confirm={translate(Texts.container.yes)}
			cancel={translate(Texts.container.no)}
			onConfirm={() => window.location.reload(true)}
			onCancel={props.cancelVersionMismatchDialog}
		/>
	}
	return null;
}



/******* S.D.G. *******/



