/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../app/Texts";


export const VersionMismatchErrorDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent danger">
				<h2>{Texts.container.versionMismatchError[props.language]}</h2>
				<div className="message">{Texts.container.versionMismatchErrorMessage[props.language]}</div>
				<button
					className="yes"
					onClick={() => window.location.reload(true)}
				>
					{Texts.container.ok[props.language]}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



