/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const MoveCards = (props) => {
    if (props.selectTargetCategory === true) {
        return <div className="modal">
            <div className="modalContent form">
                <h2>{translate(Texts.cardList.moveCards.title)}</h2>
                <div className="categoryTreeItems">
                    {props.children}
                </div>
                <div className="buttonContainer">
                    <button
                        className="yes danger"
                        onClick={props.moveCards}
                        disabled={!props.rootTargetCategory.selectedCategory}
                    >
                        {translate(Texts.cardList.moveCards.ok)}
                    </button>
                    <button
                        onClick={props.moveCardsCancelled}
                    >
                        {translate(Texts.cardList.moveCards.cancel)}
                    </button>
                </div>
            </div>
        </div>
    }
    return null;
}


/******* S.D.G. *******/



