/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const CardView = (props) => {
	return <>
		<div>naturalInputOrder: {props.naturalInputOrder !== null && props.naturalInputOrder !== undefined ? props.naturalInputOrder.toString() : ""}</div>
		<div>filter: {props.filter !== null && props.filter !== undefined ? props.filter.toString() : ""}</div>
		<div>dictionaryValue: {props.dictionaryValue !== null && props.dictionaryValue !== undefined ? props.dictionaryValue.toString() : ""}</div>
		<div>selectedCardIds: {props.selectedCardIds !== null && props.selectedCardIds !== undefined ? props.selectedCardIds.toString() : ""}</div>
		<div>movedCardIds: {props.movedCardIds !== null && props.movedCardIds !== undefined ? props.movedCardIds.toString() : ""}</div>
		<div>dragTargetCardId: {props.dragTargetCardId !== null && props.dragTargetCardId !== undefined ? props.dragTargetCardId.toString() : ""}</div>
		{props.children}
	</> 
}



/******* S.D.G. *******/



