/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const CategoryTree = (props) => {
	return <div className="categoryTree">
		{props.children}
	</div>
}



/******* S.D.G. *******/



