/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const CategoryTree = (props) => {
	return <>
		<div>filterNonScheduled: {props.filterNonScheduled !== null && props.filterNonScheduled !== undefined ? props.filterNonScheduled.toString() : ""}</div>
		<div>reverseBoxExists: {props.reverseBoxExists !== null && props.reverseBoxExists !== undefined ? props.reverseBoxExists.toString() : ""}</div>
		<div>priority: {props.priority !== null && props.priority !== undefined ? props.priority.toString() : ""}</div>
		<div>displayDeleteCategory: {props.displayDeleteCategory !== null && props.displayDeleteCategory !== undefined ? props.displayDeleteCategory.toString() : ""}</div>
		<div>dropAllowed: {props.dropAllowed !== null && props.dropAllowed !== undefined ? props.dropAllowed.toString() : ""}</div>
		<div>dropTargetCategoryId: {props.dropTargetCategoryId !== null && props.dropTargetCategoryId !== undefined ? props.dropTargetCategoryId.toString() : ""}</div>
		{props.children}
	</> 
}



/******* S.D.G. *******/



