/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import React from "react";
import {destroyToast} from "../../../gen/common/ActionFunctions";
import {translate} from "../../AppUtils";


export const MessagesItem = (props) => {
	const text = translate(props.textKey, props.args);
	return <div
		className={`toastWrapper ${props.visible === false ? "fadeOut" : ""}`}
		onClick={() => destroyToast(props.id)}
	>
		<div className={`toast ${props.type}`}>{text}</div>
	</div>
}



/******* S.D.G. *******/



