/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../app/Texts";
import {callSaveBug, cancelSaveBugDialog} from "../../../gen/common/ActionFunctions";
import {translate} from "../../AppUtils";

export const SaveBugDialog = (props) => {
	if (props.display === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{translate(Texts.container.unexpectedBug)}</h2>
				<div className="message">{translate(Texts.container.unexpectedBugMessage)}</div>
				<button
					className="yes"
					onClick={callSaveBug}
				>
					{translate(Texts.container.yes)}
				</button>
				<button
					onClick={cancelSaveBugDialog}
				>
					{translate(Texts.container.no)}
				</button>
			</div>

		</div>
	}
	return null;
}



/******* S.D.G. *******/



