/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const Login = (props) => {
    return <div className="moreMarginLine hCenter">
        <button
            className="primary"
            id="login"
            onClick={props.onClick}
        >
            {translate(Texts.login.signin)}
        </button>
    </div>
}


/******* S.D.G. *******/



