/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const Login = (props) => {
    return <button
        className="primary"
        id="login"
        onClick={props.onClick}
        {...props}
    >
        {translate(Texts.login.signin)}
    </button>
}


/******* S.D.G. *******/



