/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {login} from "../../../../../gen/login/ActionFunctions";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const Login = () => {
    return <div className="moreMarginLine hCenter">
        <button
            className="primary"
            id="login"
            onClick={login}
        >
            {translate(Texts.login.signin)}
        </button>
    </div>
}


/******* S.D.G. *******/



