// noinspection JSUnresolvedFunction

/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";
import CryptoJS from "crypto-js";

export const Password = (props) => {
    return <div className="line">
        <label htmlFor="password">
            {translate(Texts.login.password)}
        </label>
        <input
            id="password"
            type="password"
            onChange={(event) => props.onChange(CryptoJS.MD5(event.target.value).toString())}
            autoComplete="current-password"
        />
        <a onClick={props.onClick}>{translate(Texts.login.forgotPassword)}</a>
    </div>
}


/******* S.D.G. *******/



