// noinspection JSUnresolvedFunction

/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React, {useEffect, useState} from "react";

import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";
import CryptoJS from "crypto-js";

export const Password = (props) => {

    const [clearPassword, setClearPassword] = useState("");

    const onChange = (value) => {
        setClearPassword(value);
        props.onChange(CryptoJS.MD5(value).toString())
    }

    useEffect(() => {
        if (!props.value || props.value === "") {
            setClearPassword("");
        }
    }, [props.value])

    return <>
        <input
            id="password"
            type="password"
            value={clearPassword}
            onChange={(event) => onChange(event.target.value)}
            autoComplete="current-password"
            placeholder={translate(Texts.login.password)}
        />
        <a onClick={props.onClick}>{translate(Texts.login.forgotPassword)}</a>
    </>
}


/******* S.D.G. *******/



