/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {toggleSaveInLocalStorage} from "../../../../../gen/login/ActionFunctions";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const SaveInLocalStorage = (props) => {
    return <div className="line">
        <input
            id="saveInLocalStorage"
            type="checkbox"
            onChange={toggleSaveInLocalStorage}
        />
        <label htmlFor="saveInLocalStorage">
            {translate(Texts.login.saveInLocalStorage)}
        </label>
        <div className="small-font">{translate(Texts.login.saveInLocalStorageHint)}</div>
    </div>
}


/******* S.D.G. *******/



