/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {usernameChanged} from "../../../../../gen/login/ActionFunctions";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";
import {route} from "../../../../../gen/common/ActionFunctions";

export const Username = (props) => {
    return <div className="line">
        <label htmlFor="username">
            {translate(Texts.login.username)}
        </label>
        <input
            id="username"
            type="text"
            onChange={(event) => usernameChanged(event.target.value)}
        />
        <a id="registration" onClick={() => route("#registration")}>{translate(Texts.login.registration)}</a>
    </div>
}


/******* S.D.G. *******/



