/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";

export const Archive = (props) => {
    const onArchiveClick = (e) => {
        e.stopPropagation();
        props.onClick(!props.archived, props.boxId).then();
    }

    return (
        <i
            className="fas fa-archive"
            onClick={(e) => onArchiveClick(e)}
            title={translate(Texts.box.archiveBox)}
        />
    )
}


/******* S.D.G. *******/



