/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../../../../AppUtils";
import {Texts} from "../../../../../../app/Texts";


export const Statistics = (props) => {
    const onStatisticsClick = (e) => {
        e.stopPropagation();
        props.onClick(props.boxId)
    }

    if (props.archived === true) {
        return null;
    }

    return (
        <i
            className="far fa-calendar-alt"
            onClick={(e) => onStatisticsClick(e)}
            title={translate(Texts.box.statistics)}
        />
    )
}


/******* S.D.G. *******/



