/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const CardDuplicatesItem = (props) => {
	return <>
		<div>cardId: {props.cardId !== null && props.cardId !== undefined ? props.cardId.toString() : ""}</div>
		<div>given: {props.given !== null && props.given !== undefined ? props.given.toString() : ""}</div>
		<div>wanted: {props.wanted !== null && props.wanted !== undefined ? props.wanted.toString() : ""}</div>
		<div>cardAuthor: {props.cardAuthor !== null && props.cardAuthor !== undefined ? props.cardAuthor.toString() : ""}</div>
		<div>cardIndex: {props.cardIndex !== null && props.cardIndex !== undefined ? props.cardIndex.toString() : ""}</div>
		<div>categoryId: {props.categoryId !== null && props.categoryId !== undefined ? props.categoryId.toString() : ""}</div>
		<div>rootCategoryId: {props.rootCategoryId !== null && props.rootCategoryId !== undefined ? props.rootCategoryId.toString() : ""}</div>
		<div>next: {props.next !== null && props.next !== undefined ? props.next.toString() : ""}</div>
		<div>categoryName: {props.categoryName !== null && props.categoryName !== undefined ? props.categoryName.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



