/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const CardDuplicatesItem = (props) => {
	return <>
		<h1>CardDuplicatesItem</h1>
		<ul>
			<li>cardId: {props.cardId !== null && props.cardId !== undefined ? props.cardId.toString() : ""}</li>
			<li>given: {props.given !== null && props.given !== undefined ? props.given.toString() : ""}</li>
			<li>wanted: {props.wanted !== null && props.wanted !== undefined ? props.wanted.toString() : ""}</li>
			<li>cardAuthor: {props.cardAuthor !== null && props.cardAuthor !== undefined ? props.cardAuthor.toString() : ""}</li>
			<li>cardIndex: {props.cardIndex !== null && props.cardIndex !== undefined ? props.cardIndex.toString() : ""}</li>
			<li>categoryId: {props.categoryId !== null && props.categoryId !== undefined ? props.categoryId.toString() : ""}</li>
			<li>rootCategoryId: {props.rootCategoryId !== null && props.rootCategoryId !== undefined ? props.rootCategoryId.toString() : ""}</li>
			<li>next: {props.next !== null && props.next !== undefined ? props.next.toString() : ""}</li>
			<li>categoryName: {props.categoryName !== null && props.categoryName !== undefined ? props.categoryName.toString() : ""}</li>
		</ul>
	</> 
}



/******* S.D.G. *******/



