/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../../../app/Texts";
import {cancelDeleteCard, deleteCard} from "../../../../../../gen/card/ActionFunctions";
import {translate} from "../../../../../AppUtils";


export const DeleteCard = (props) => {
	if (props.confirmDelete === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{translate(Texts.cardList.confirmDelete.title)}</h2>
				<div className="message">{translate(Texts.cardList.confirmDelete.message)}</div>
				<button
					className="yes danger"
					onClick={deleteCard}
				>
					{translate(Texts.cardList.confirmDelete.ok)}
				</button>
				<button
					onClick={cancelDeleteCard}
				>
					{translate(Texts.cardList.confirmDelete.cancel)}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



