/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const DeleteCard = (props) => {
	return <>
		<div>confirmDelete: {props.confirmDelete !== null && props.confirmDelete !== undefined ? props.confirmDelete.toString() : ""}</div>
		<div>cardId: {props.cardId !== null && props.cardId !== undefined ? props.cardId.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



