/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const DeleteCard = (props) => {
	return <>
		<h1>DeleteCard</h1>
		<ul>
			<li>confirmDelete: {props.confirmDelete !== null && props.confirmDelete !== undefined ? props.confirmDelete.toString() : ""}</li>
			<li>cardId: {props.cardId !== null && props.cardId !== undefined ? props.cardId.toString() : ""}</li>
		</ul>
	</> 
}



/******* S.D.G. *******/



