/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const NewCard = (props) => {
	return <>
		<h1>NewCard</h1>
		<ul>
			<li>given: {props.given !== null && props.given !== undefined ? props.given.toString() : ""}</li>
			<li>wanted: {props.wanted !== null && props.wanted !== undefined ? props.wanted.toString() : ""}</li>
			<li>index: {props.index !== null && props.index !== undefined ? props.index.toString() : ""}</li>
			<li>displaySpinner: {props.displaySpinner !== null && props.displaySpinner !== undefined ? props.displaySpinner.toString() : ""}</li>
		</ul>
	</> 
}



/******* S.D.G. *******/



