/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {emailChanged} from "../../../../../gen/registration/ActionFunctions";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const Email = (props) => {
    return <div className="line">
        <label>{translate(Texts.registration.email)}</label>
        <div className="inputContainer">
            <input
                type="text"
                value={props.value}
                autoComplete="off"
                onChange={(event) => emailChanged(event.target.value)}
                id="email"
            />
            {props.emailInvalid === true && props.value.length > 0 &&
            <i className="fas fa-times outside error"/>}
        </div>
    </div>
}


/******* S.D.G. *******/



