// noinspection JSUnresolvedFunction

/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";
import CryptoJS from "crypto-js";

export const PasswordRepetition = (props) => {
    return         <div className="inputContainer">
            <input
                type="password"
                onChange={(e) => props.onChange(CryptoJS.MD5(e.target.value).toString())}
                autoComplete="off"
                id="passwordRepetition"
                placeholder={translate(Texts.registration.passwordRepetition)}
            />
            {props.passwordMismatch === true && <i className="fas fa-times error"/>}
        </div>
}


/******* S.D.G. *******/



