/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {passwordChanged} from "../../../../../gen/registration/ActionFunctions";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";
import CryptoJS from "crypto-js";

export const Password = (props) => {
    return <div className="line">
        <label>{translate(Texts.registration.password)}</label>
        <div className="inputContainer">
            <input
                type="password"
                onChange={(e) => passwordChanged(CryptoJS.MD5(e.target.value).toString())}
                autoComplete="off"
                id="password"
            />
        </div>
    </div>
}


/******* S.D.G. *******/



