/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const Username = (props) => {
    return <div className="inputContainer">
        <input
            type="text"
            value={props.value}
            onChange={(event) => props.onChange(event.target.value)}
            autoComplete="off"
            id="username"
            placeholder={translate(Texts.registration.username)}
        />
        {props.displayUsernameSpinner === true &&
            <i className="fas fa-cog fa-spin inside"/>}
        {props.available === true && props.value.length > 0 &&
            <i className="fas fa-check success"/>}
        {props.available === false && props.value.length > 0 &&
            <i className="fas fa-times error"/>}
    </div>
}


/******* S.D.G. *******/



