/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const Buttons = (props) => {
	return <div className="moreMarginLine text-center">
		{props.children}
	</div>
}



/******* S.D.G. *******/



