/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const Buttons = (props) => {
	return <div className="buttonContainer">
		{props.children}
	</div>
}



/******* S.D.G. *******/



