/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const Username = (props) => {
    return <input
        id="username"
        value={props.username}
        type="text"
        autoComplete="new-password"
        onChange={(e) => props.onChange(e.target.value)}
        placeholder={translate(Texts.forgotPassword.username)}
    />
}


/******* S.D.G. *******/



