/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const NextCard = (props) => {
	return <>
		<div>cardId: {props.cardId !== null && props.cardId !== undefined ? props.cardId.toString() : ""}</div>
		<div>categoryId: {props.categoryId !== null && props.categoryId !== undefined ? props.categoryId.toString() : ""}</div>
		<div>categoryName: {props.categoryName !== null && props.categoryName !== undefined ? props.categoryName.toString() : ""}</div>
		<div>count: {props.count !== null && props.count !== undefined ? props.count.toString() : ""}</div>
		<div>given: {props.given !== null && props.given !== undefined ? props.given.toString() : ""}</div>
		<div>lastQuality: {props.lastQuality !== null && props.lastQuality !== undefined ? props.lastQuality.toString() : ""}</div>
		<div>rootCategoryId: {props.rootCategoryId !== null && props.rootCategoryId !== undefined ? props.rootCategoryId.toString() : ""}</div>
		<div>scheduledCardId: {props.scheduledCardId !== null && props.scheduledCardId !== undefined ? props.scheduledCardId.toString() : ""}</div>
		<div>reinforceCardId: {props.reinforceCardId !== null && props.reinforceCardId !== undefined ? props.reinforceCardId.toString() : ""}</div>
		<div>scheduledDate: {props.scheduledDate !== null && props.scheduledDate !== undefined ? props.scheduledDate.toString() : ""}</div>
		<div>scoredDate: {props.scoredDate !== null && props.scoredDate !== undefined ? props.scoredDate.toString() : ""}</div>
		<div>wanted: {props.wanted !== null && props.wanted !== undefined ? props.wanted.toString() : ""}</div>
		<div>index: {props.index !== null && props.index !== undefined ? props.index.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



