/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractBoxClickCommand from "../../../gen/box/commands/AbstractBoxClickCommand";

export default class BoxClickCommand extends AbstractBoxClickCommand {
    execute(data) {
    	return data;
    }
}




/******* S.D.G. *******/



