/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractBoxClickCommand from "../../../gen/box/commands/AbstractBoxClickCommand";

export default class BoxClickCommand extends AbstractBoxClickCommand {
    execute(data) {
        if (data.openTodaysCards > 0) {
            this.addQueryCardsOutcome(data)
        } else {
            this.addAuthorViewOutcome(data)
        }
    	return data;
    }
}




/******* S.D.G. *******/



