/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCallScoreReinforceCardCommand from "../../../gen/box/commands/AbstractCallScoreReinforceCardCommand";

export default class CallScoreReinforceCardCommand extends AbstractCallScoreReinforceCardCommand {

    validateCommandData() {
        return true;
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
        resolve(data);
    }
    handleError(data, resolve, reject) {
        reject(data.error);
    }
}




/******* S.D.G. *******/



