/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCallSortCardOutCommand from "../../../gen/box/commands/AbstractCallSortCardOutCommand";

export default class CallSortCardOutCommand extends AbstractCallSortCardOutCommand {

    validateCommandData(data) {
        data.cardIds = [];
        data.cardIds[0] = data.cardId;
        return true;
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
        resolve(data);
    }
    handleError(data, resolve, reject) {
        reject(data.error);
    }
}




/******* S.D.G. *******/



