/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteBoxCommand from "../../../gen/box/commands/AbstractDeleteBoxCommand";
import {Texts} from "../../app/Texts";

export default class DeleteBoxCommand extends AbstractDeleteBoxCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.confirmDelete = false;
        data.boxId = undefined;
        this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve) {
        this.addErrorOutcome(data);
        data.textKey = Texts.messages.cannotDeleteSharedBox;
        data.confirmDelete = false;
        data.boxId = undefined;
        resolve(data);
    }
}


/******* S.D.G. *******/



