/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import AbstractDisplayWantedCommand from "../../../gen/box/commands/AbstractDisplayWantedCommand";

export default class DisplayWantedCommand extends AbstractDisplayWantedCommand {
    execute(data) {
        data.index += 1;
        if (data.wantedItemsLength === data.index) {
            data.enableScoreButtons = true;
        }
        this.addOkOutcome(data);
        return data;
    }
}


/******* S.D.G. *******/



