/********************************************************************************
 * generated by de.acegen 1.6.5
 ********************************************************************************/




import AbstractFilterActiveCardListWithLastQualityChangedCommand from "../../../gen/box/commands/AbstractFilterActiveCardListWithLastQualityChangedCommand";

export default class FilterActiveCardListWithLastQualityChangedCommand extends AbstractFilterActiveCardListWithLastQualityChangedCommand {
    execute(data) {
        const index = data.selectedLastQualityFilters.indexOf(data.lastQualityFilter);
        if (index >= 0) {
            data.selectedLastQualityFilters.splice(index, 1);
        } else {
            data.selectedLastQualityFilters.push(data.lastQualityFilter);
        }
    	this.addOkOutcome(data);
        console.log(data);
    	return data;
    }
}




/******* S.D.G. *******/



