/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInitBoxesForDayCommand from "../../../gen/box/commands/AbstractInitBoxesForDayCommand";

export default class InitBoxesForDayCommand extends AbstractInitBoxesForDayCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



