/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractLoadSettingsCommand from "../../../gen/box/commands/AbstractLoadSettingsCommand";

export default class LoadSettingsCommand extends AbstractLoadSettingsCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.boxSettings.maxCardsPerDay = data.boxSettings.maxCardsPerDay ? data.boxSettings.maxCardsPerDay : "";
        data.boxSettings.maxInterval = data.boxSettings.maxInterval ? data.boxSettings.maxInterval : "";
        data.boxSettings.tooManyCardsWarning = !!(data.boxSettings.maxCardsPerDay && data.boxSettings.maxInterval && data.boxSettings.allActiveCards > data.boxSettings.maxCardsPerDay * data.boxSettings.maxInterval);
        data.boxSettings.givenLanguage = !data.boxSettings.givenLanguage ? "": data.boxSettings.givenLanguage;
        data.boxSettings.wantedLanguage = !data.boxSettings.wantedLanguage ? "": data.boxSettings.wantedLanguage;
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



