/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import AbstractScoreCardCommand from "../../../gen/box/commands/AbstractScoreCardCommand";
import {Texts} from "../../app/Texts";

export default class ScoreCardCommand extends AbstractScoreCardCommand {

    validateCommandData() {
        return true;
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
        if (data.intervalDifference > 0) {
            this.addShowWarningToastOutcome(data);
            if (data.intervalDifference === 1) {
                data.textKey = Texts.messages.intervalOffsetPostponedSingular;
            } else if (data.intervalDifference > 1) {
                data.textKey = Texts.messages.intervalOffsetPostponed;
                data.args = [data.intervalDifference];
            }
        } else if (data.intervalDifference < 0) {
            this.addShowInfoToastOutcome(data)
            if (data.intervalDifference === -1) {
                data.textKey = Texts.messages.intervalOffsetMovedForwardSingular;
            } else if (data.intervalDifference < -1) {
                data.textKey = Texts.messages.intervalOffsetMovedForward;
                data.args = [data.intervalDifference * (-1)];
            }
        }
        resolve(data);
    }

    handleError(data, resolve, reject) {
        reject(data.error);
    }
}


/******* S.D.G. *******/



