/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractSortCardOutCommand from "../../../gen/box/commands/AbstractSortCardOutCommand";

export default class SortCardOutCommand extends AbstractSortCardOutCommand {
    execute(data) {
        data.disableScoreButtons = true;
        data.disableSortOutButton = true;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



