/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractDisplayErrorToastCommand from "../../../gen/common/commands/AbstractDisplayErrorToastCommand";
import {pushMessage} from "./DisplayToastCommand";

export default class DisplayErrorToastCommand extends AbstractDisplayErrorToastCommand {
    execute(data) {
        pushMessage(data, "error");
        this.addOkOutcome(data);
        return data;
    }
}




/******* S.D.G. *******/



