/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import AbstractDisplayToastCommand from "../../../gen/common/commands/AbstractDisplayToastCommand";

export function pushMessage(data, type) {
    const message = {
        id: data.messages.length,
        visible: true,
        type,
        textKey: data.textKey,
        args: data.args
    }
    data.messages.push(message);
    data.id = message.id;
    return data
}

export default class DisplayToastCommand extends AbstractDisplayToastCommand {
    execute(data) {
        pushMessage(data, "info");
        this.addOkOutcome(data);
        return data;
    }
}


/******* S.D.G. *******/



