/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetUserInfoCommand from "../../../gen/common/commands/AbstractGetUserInfoCommand";

export default class GetUserInfoCommand extends AbstractGetUserInfoCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve) {
        this.addErrorOutcome(data);
        resolve(data);
    }
}




/******* S.D.G. *******/



