/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractHideSaveBugDialogCommand from "../../../gen/common/commands/AbstractHideSaveBugDialogCommand";
import {Texts} from "../../app/Texts";

export default class HideSaveBugDialogCommand extends AbstractHideSaveBugDialogCommand {
    execute(data) {
        data.display = false;
        data.textKey = Texts.messages.thankYou;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



