/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToBoxSettingsCommand from "../../../gen/common/commands/AbstractRouteToBoxSettingsCommand";

export default class RouteToBoxSettingsCommand extends AbstractRouteToBoxSettingsCommand {
    execute(data) {
    	this.addOkOutcome(data);
        data.hash = `#box/settings/${data.boxId}`
    	return data;
    }
}




/******* S.D.G. *******/



