/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToPrivacyPolicyCommand from "../../../gen/common/commands/AbstractRouteToPrivacyPolicyCommand";

export default class RouteToPrivacyPolicyCommand extends AbstractRouteToPrivacyPolicyCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



