/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToDefaultCommand from "../../../gen/common/commands/AbstractRouteToDefaultCommand";

export default class RouteToDefaultCommand extends AbstractRouteToDefaultCommand {
    execute(data) {
    	this.addOkOutcome(data);
        data.hash = "#"
    	return data;
    }
}




/******* S.D.G. *******/



