/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToHomeCommand from "../../../gen/common/commands/AbstractRouteToHomeCommand";

export default class RouteToHomeCommand extends AbstractRouteToHomeCommand {
    execute(data) {
    	this.addOkOutcome(data);
        data.hash = "#"
    	return data;
    }
}




/******* S.D.G. *******/



