/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToLoginCommand from "../../../gen/common/commands/AbstractRouteToLoginCommand";

export default class RouteToLoginCommand extends AbstractRouteToLoginCommand {
    execute(data) {
    	this.addOkOutcome(data);
        data.hash = "#"
    	return data;
    }
}




/******* S.D.G. *******/



