/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToAuthorViewCommand from "../../../gen/common/commands/AbstractRouteToAuthorViewCommand";

export default class RouteToAuthorViewCommand extends AbstractRouteToAuthorViewCommand {
    execute(data) {
    	this.addOkOutcome(data);
        data.hash = `#categories/${data.categoryId}${data.reverse ? "/reverse" : ""}`;
    	return data;
    }
}




/******* S.D.G. *******/



