/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractRouteToActiveCardsCommand from "../../../gen/common/commands/AbstractRouteToActiveCardsCommand";

export default class RouteToActiveCardsCommand extends AbstractRouteToActiveCardsCommand {
    execute(data) {
    	this.addOkOutcome(data);
        data.hash = `#box/active-cards/${data.boxId}`
    	return data;
    }
}




/******* S.D.G. *******/



