/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

import { route } from "../../../../../../gen/common/ActionFunctions";

export const Cancel = (props) => {
	return <button 
		className="button"
		onClick={(event) => route(props.hash)}
	>
		cancel
	</button>
}



/******* S.D.G. *******/



