/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import {translate} from "../../../../AppUtils";
import {Texts} from "../../../../app/Texts";

export const BoxListItem = (props) => {
    if (props.archived === true) {
        return <a className="tile box">
            <h2>
                {!props.editable ?
                    translate(Texts.box.sharedTitle, [props.categoryName, props.categoryAuthor]) :
                    props.categoryName}
                {props.reverse ? <i className="fas fa-arrows-alt-h withmarginleft"/> : null}
            </h2>
            <br/>
            {props.children}
        </a>
    }

    return <a
        className="tile box active"
        id={props.boxId}
        onClick={() => props.onClick(props.boxId, props.openTodaysCards, props.categoryId, props.reverse)}>
        <h2>
            {!props.editable ?
                translate(Texts.box.sharedTitle, [props.categoryName, props.categoryAuthor]) :
                props.categoryName}
            {props.reverse ? <i className="fas fa-arrows-alt-h withmarginleft"/> : null}
        </h2>
        {props.openTodaysCards > 0 ? <span className="badge">{props.openTodaysCards}</span> : null}
        {props.children}
    </a>
}


/******* S.D.G. *******/



