/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";
import "./boxList.scss"

export const BoxListItem = (props) => {
    return <div
        className="tile"
        id={props.boxId}
        onClick={props.archived ? () => {} : () => props.onClick(props.boxId, props.openTodaysCards, props.categoryId, props.reverse)}
    >
        {props.openTodaysCards > 0 ? <span className="badge">{props.openTodaysCards}</span> : null}
        {props.children}
    </div>
}


/******* S.D.G. *******/



