/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {Texts} from "../../../../app/Texts";
import {cancelDeleteBox, deleteBox} from "../../../../../gen/box/ActionFunctions";
import {translate} from "../../../../AppUtils";


export const DeleteBox = (props) => {
	if (props.confirmDelete === true) {
		return <div className="modal">
			<div className="modalContent">
				<h2>{translate(Texts.box.confirmDelete.title)}</h2>
				<div className="message">{translate(Texts.box.confirmDelete.message)}</div>
				<button
					className="yes danger"
					onClick={deleteBox}
				>
					{translate(Texts.box.confirmDelete.ok)}
				</button>
				<button
					onClick={cancelDeleteBox}
				>
					{translate(Texts.box.confirmDelete.cancel)}
				</button>
			</div>
		</div>
	}
	return null;
}



/******* S.D.G. *******/



