/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const DeleteBox = (props) => {
	return <>
		<div>confirmDelete: {props.confirmDelete !== null && props.confirmDelete !== undefined ? props.confirmDelete.toString() : ""}</div>
		<div>boxId: {props.boxId !== null && props.boxId !== undefined ? props.boxId.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



