/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

export const NewBox = (props) => {
    return <div
        className="tile box-create"
        id="new"
        onClick={props.onClick}
    >
        <i className="fas fa-plus-circle fa-2x"/>
    </div>
}


/******* S.D.G. *******/



