/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

import { route } from "../../../../../gen/common/ActionFunctions";

export const NewBox = (props) => {
	return <a
		className="tile box-create"
		onClick={() => route("#box/create")}
	>
		<div className="text-center">
			<i className="fas fa-plus-circle fa-2x"/>
		</div>
	</a>
}



/******* S.D.G. *******/



