/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const NewBox = (props) => {
	return <a
		className="tile box-create"
		onClick={props.onClick}
	>
		<div className="text-center">
			<i className="fas fa-plus-circle fa-2x"/>
		</div>
	</a>
}



/******* S.D.G. *******/



