/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCollapseTreeItemCommand from "../../../gen/card/commands/AbstractCollapseTreeItemCommand";
import {findCategory, isCategoryChildOfParent} from "../../category/utils/CategoryTreeUtils";

export default class CollapseTreeItemCommand extends AbstractCollapseTreeItemCommand {
    execute(data) {
        let category = findCategory(data.rootTargetCategory.childCategories, data.categoryId);
        category.expanded = false;
        if (data.selectedCategory && isCategoryChildOfParent(category, data.selectedCategory.categoryId)) {
            this.addSelectParentCategoryOutcome(data);
        } else {
            this.addOkOutcome(data);
        }
    	return data;
    }
}




/******* S.D.G. *******/



