/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCollapseTreeItemInMoveDialogCommand from "../../../gen/card/commands/AbstractCollapseTreeItemInMoveDialogCommand";
import {collapseTreeItem} from "../../category/commands/CollapseTreeItemCommand";

export default class CollapseTreeItemInMoveDialogCommand extends AbstractCollapseTreeItemInMoveDialogCommand {
    execute(data) {
        return collapseTreeItem(data, data.rootCategoryInMoveDialog, this.addOkOutcome, this.addSelectParentCategoryOutcome);
    }
}




/******* S.D.G. *******/



