/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateCardCommand from "../../../gen/card/commands/AbstractCreateCardCommand";

export default class CreateCardCommand extends AbstractCreateCardCommand {

    validateCommandData(data) {
        if (data.givenImage && data.givenImage.length > 0) {
            data.given = data.givenImage
        }
        if (data.wantedImage && data.wantedImage.length > 0) {
            data.wanted = data.wantedImage
        }
    	return true;
    }

    handleResponse(data, resolve) {
        data.newCard = {
            given: "",
            givenImage: null,
            wanted: "",
            wantedImage: null,
            displaySpinner: false,
        };
        data.cardDuplicates = [];
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



