/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateCardCommand from "../../../gen/card/commands/AbstractCreateCardCommand";

export default class CreateCardCommand extends AbstractCreateCardCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        data.newCard = {
            given: "",
            wanted: "",
            displaySpinner: false,
        };
        data.cardDuplicates = [];
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



