/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractExpandTreeItemCommand from "../../../gen/card/commands/AbstractExpandTreeItemCommand";
import {findCategory} from "../../category/utils/CategoryTreeUtils";

export default class ExpandTreeItemCommand extends AbstractExpandTreeItemCommand {
    execute(data) {
        let category = findCategory(data.rootTargetCategory.childCategories, data.categoryId);
        category.expanded = true;
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



