/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractGivenImageOfNewCardChangedCommand from "../../../gen/card/commands/AbstractGivenImageOfNewCardChangedCommand";

export default class GivenImageOfNewCardChangedCommand extends AbstractGivenImageOfNewCardChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



