/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractGivenImageOfEditedCardChangedCommand from "../../../gen/card/commands/AbstractGivenImageOfEditedCardChangedCommand";

export default class GivenImageOfEditedCardChangedCommand extends AbstractGivenImageOfEditedCardChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



