/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCardsCancelledCommand from "../../../gen/card/commands/AbstractMoveCardsCancelledCommand";

export default class MoveCardsCancelledCommand extends AbstractMoveCardsCancelledCommand {
    execute(data) {
        data.moveCards = {
            selectTargetCategory: false,
            rootCategoryInMoveDialog: null,
        };
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



