/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractToggleCardOrderCommand from "../../../gen/card/commands/AbstractToggleCardOrderCommand";

export default class ToggleCardOrderCommand extends AbstractToggleCardOrderCommand {

    validateCommandData(data) {
        if (data.down === undefined) {
            data.down = false;
        }
        if (data.selectedCardIds === undefined || data.selectedCardIds.length !== 1) {
            return false;
        }
        data.cardId = data.selectedCardIds[0];
        data.keepSelectedCards = true
    	return true;
    }

    handleResponse(data, resolve, reject) {
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



