/********************************************************************************
 * generated by de.acegen 1.6.5
 ********************************************************************************/




import AbstractTranslateCommand from "../../../gen/card/commands/AbstractTranslateCommand";

export default class TranslateCommand extends AbstractTranslateCommand {

    validateCommandData(data) {
        if (data.naturalInputOrder === true) {
            if (data.wanted) {
                this.addTargetNotEmtpyOutcome(data)
                return false
            }
            data.sourceValue = data.given
            data.sourceLanguage = data.givenLanguage
            data.targetLanguage = data.wantedLanguage
        } else {
            if (data.given) {
                this.addTargetNotEmtpyOutcome(data)
                return false
            }
            data.sourceValue = data.wanted
            data.sourceLanguage = data.wantedLanguage
            data.targetLanguage = data.givenLanguage
        }
        if (!data.sourceValue) {
            this.addEmptyOutcome(data)
            return false
        }
    	return true;
    }

    handleResponse(data, resolve) {
        if (data.naturalInputOrder === true) {
            this.addWantedFetchedOutcome(data)
            data.wanted = data.targetValue
        } else {
            this.addGivenFetchedOutcome(data)
            data.given = data.targetValue
        }
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



