/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateCardCommand from "../../../gen/card/commands/AbstractUpdateCardCommand";

export default class UpdateCardCommand extends AbstractUpdateCardCommand {

    validateCommandData(data) {
        if (data.givenImage && data.givenImage.length > 0) {
            data.given = data.givenImage
        }
        if (data.wantedImage && data.wantedImage.length > 0) {
            data.wanted = data.wantedImage
        }
    	return true;
    }

    handleResponse(data, resolve) {
        data.editedCard = {
            cardId: "",
            given: "",
            givenImage: null,
            wanted: "",
            wantedImage: null,
        };
    	this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



