/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractWantedImageOfEditedCardChangedCommand from "../../../gen/card/commands/AbstractWantedImageOfEditedCardChangedCommand";

export default class WantedImageOfEditedCardChangedCommand extends AbstractWantedImageOfEditedCardChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



