/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractWantedImageOfNewCardChangedCommand from "../../../gen/card/commands/AbstractWantedImageOfNewCardChangedCommand";

export default class WantedImageOfNewCardChangedCommand extends AbstractWantedImageOfNewCardChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



