/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCancelDeleteCardAction from "../../../gen/card/actions/AbstractCancelDeleteCardAction";

export default class CancelDeleteCardAction extends AbstractCancelDeleteCardAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



