/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractChangeCardOrderAction from "../../../gen/card/actions/AbstractChangeCardOrderAction";

export default class ChangeCardOrderAction extends AbstractChangeCardOrderAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



