/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCollapseTreeItemInMoveDialogAction from "../../../gen/card/actions/AbstractCollapseTreeItemInMoveDialogAction";

export default class CollapseTreeItemInMoveDialogAction extends AbstractCollapseTreeItemInMoveDialogAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



