/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractCollapseTreeItemAction from "../../../gen/card/actions/AbstractCollapseTreeItemAction";

export default class CollapseTreeItemAction extends AbstractCollapseTreeItemAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



