/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteCardClickAction from "../../../gen/card/actions/AbstractDeleteCardClickAction";

export default class DeleteCardClickAction extends AbstractDeleteCardClickAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



