/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractExpandTreeItemInMoveDialogAction from "../../../gen/card/actions/AbstractExpandTreeItemInMoveDialogAction";

export default class ExpandTreeItemInMoveDialogAction extends AbstractExpandTreeItemInMoveDialogAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



