/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractGivenImageOfNewCardChangedAction from "../../../gen/card/actions/AbstractGivenImageOfNewCardChangedAction";

export default class GivenImageOfNewCardChangedAction extends AbstractGivenImageOfNewCardChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



