/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractGivenImageOfEditedCardChangedAction from "../../../gen/card/actions/AbstractGivenImageOfEditedCardChangedAction";

export default class GivenImageOfEditedCardChangedAction extends AbstractGivenImageOfEditedCardChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



