/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCardsCancelledAction from "../../../gen/card/actions/AbstractMoveCardsCancelledAction";

export default class MoveCardsCancelledAction extends AbstractMoveCardsCancelledAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



