/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractMoveCardsClickedAction from "../../../gen/card/actions/AbstractMoveCardsClickedAction";

export default class MoveCardsClickedAction extends AbstractMoveCardsClickedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



