/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPassValueToDictionaryAction from "../../../gen/card/actions/AbstractPassValueToDictionaryAction";

export default class PassValueToDictionaryAction extends AbstractPassValueToDictionaryAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



