/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractSelectTargetCategoryAction from "../../../gen/card/actions/AbstractSelectTargetCategoryAction";

export default class SelectTargetCategoryAction extends AbstractSelectTargetCategoryAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



