/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractSortSelectedCardsOutAction from "../../../gen/card/actions/AbstractSortSelectedCardsOutAction";

export default class SortSelectedCardsOutAction extends AbstractSortSelectedCardsOutAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



