/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractToggleCardOrderAction from "../../../gen/card/actions/AbstractToggleCardOrderAction";

export default class ToggleCardOrderAction extends AbstractToggleCardOrderAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



