/********************************************************************************
 * generated by de.acegen 1.6.5
 ********************************************************************************/




import AbstractTranslateAction from "../../../gen/card/actions/AbstractTranslateAction";

export default class TranslateAction extends AbstractTranslateAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



