/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractWantedImageOfNewCardChangedAction from "../../../gen/card/actions/AbstractWantedImageOfNewCardChangedAction";

export default class WantedImageOfNewCardChangedAction extends AbstractWantedImageOfNewCardChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



