/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const ActiveCardListItem = (props) => {
	return <>
		<div>cardId: {props.cardId !== null && props.cardId !== undefined ? props.cardId.toString() : ""}</div>
		<div>given: {props.given !== null && props.given !== undefined ? props.given.toString() : ""}</div>
		<div>wanted: {props.wanted !== null && props.wanted !== undefined ? props.wanted.toString() : ""}</div>
		<div>cardAuthor: {props.cardAuthor !== null && props.cardAuthor !== undefined ? props.cardAuthor.toString() : ""}</div>
		<div>cardIndex: {props.cardIndex !== null && props.cardIndex !== undefined ? props.cardIndex.toString() : ""}</div>
		<div>categoryId: {props.categoryId !== null && props.categoryId !== undefined ? props.categoryId.toString() : ""}</div>
		<div>rootCategoryId: {props.rootCategoryId !== null && props.rootCategoryId !== undefined ? props.rootCategoryId.toString() : ""}</div>
		<div>priority: {props.priority !== null && props.priority !== undefined ? props.priority.toString() : ""}</div>
		<div>next: {props.next !== null && props.next !== undefined ? props.next.toString() : ""}</div>
		<div>ef: {props.ef !== null && props.ef !== undefined ? props.ef.toString() : ""}</div>
		<div>interval: {props.interval !== null && props.interval !== undefined ? props.interval.toString() : ""}</div>
		<div>count: {props.count !== null && props.count !== undefined ? props.count.toString() : ""}</div>
		<div>lastQuality: {props.lastQuality !== null && props.lastQuality !== undefined ? props.lastQuality.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



