/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const Email = (props) => {
	return <input
		type="text"
		value={props.value}
		id="email"
		readOnly={true}
	/>
}



/******* S.D.G. *******/



