/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const Username = (props) => {
	return <input
		type="text"
		value={props.value}
		id="username"
		readOnly={true}
	/>
}



/******* S.D.G. *******/



