/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../../../AppUtils";
import {Texts} from "../../../../../../../../app/Texts";

export const MoveUp = (props) => {
	return <button
		onClick={() => props.onClick(false)}
		title={translate(Texts.cardList.moveUp)}
	>
		<i className="fas fa-angle-up"></i>
	</button>
}



/******* S.D.G. *******/



