/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../../../AppUtils";
import {Texts} from "../../../../../../../../app/Texts";

export const SortCardsOut = (props) => {
	return <button
		onClick={props.onClick}
		title={translate(Texts.cardList.sortSelectedCardsOut)}
		disabled={props.selectedCardIds.length === 0}
	>
		<i className="far fa-calendar-minus"></i>
	</button>
}



/******* S.D.G. *******/



