/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";
import {translate} from "../../../../../../../../AppUtils";
import {Texts} from "../../../../../../../../app/Texts";

export const ToggleInputOrder = (props) => {
	return <button
		onClick={props.onClick}
		title={translate(Texts.categoryTree.toggleInputOrder)}
	>
		<i className="fas fa-exchange-alt"/>
	</button>
}



/******* S.D.G. *******/



