/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const BoxSettings = (props) => {
	return <>
		<div>maxIntervalInvalid: {props.maxIntervalInvalid !== null && props.maxIntervalInvalid !== undefined ? props.maxIntervalInvalid.toString() : ""}</div>
		<div>maxCardsPerDayInvalid: {props.maxCardsPerDayInvalid !== null && props.maxCardsPerDayInvalid !== undefined ? props.maxCardsPerDayInvalid.toString() : ""}</div>
		<div>tooManyCardsStatus: {props.tooManyCardsStatus !== null && props.tooManyCardsStatus !== undefined ? props.tooManyCardsStatus.toString() : ""}</div>
		<div>dictionaryLookupInvalid: {props.dictionaryLookupInvalid !== null && props.dictionaryLookupInvalid !== undefined ? props.dictionaryLookupInvalid.toString() : ""}</div>
		<div>boxId: {props.boxId !== null && props.boxId !== undefined ? props.boxId.toString() : ""}</div>
		<div>maxInterval: {props.maxInterval !== null && props.maxInterval !== undefined ? props.maxInterval.toString() : ""}</div>
		<div>maxCardsPerDay: {props.maxCardsPerDay !== null && props.maxCardsPerDay !== undefined ? props.maxCardsPerDay.toString() : ""}</div>
		<div>categoryName: {props.categoryName !== null && props.categoryName !== undefined ? props.categoryName.toString() : ""}</div>
		<div>dictionaryLookup: {props.dictionaryLookup !== null && props.dictionaryLookup !== undefined ? props.dictionaryLookup.toString() : ""}</div>
		<div>givenLanguage: {props.givenLanguage !== null && props.givenLanguage !== undefined ? props.givenLanguage.toString() : ""}</div>
		<div>wantedLanguage: {props.wantedLanguage !== null && props.wantedLanguage !== undefined ? props.wantedLanguage.toString() : ""}</div>
		<div>categoryId: {props.categoryId !== null && props.categoryId !== undefined ? props.categoryId.toString() : ""}</div>
		<div>deletable: {props.deletable !== null && props.deletable !== undefined ? props.deletable.toString() : ""}</div>
		<div>allActiveCards: {props.allActiveCards !== null && props.allActiveCards !== undefined ? props.allActiveCards.toString() : ""}</div>
		<div>allCards: {props.allCards !== null && props.allCards !== undefined ? props.allCards.toString() : ""}</div>
	</> 
}



/******* S.D.G. *******/



