/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

import { registerUser } from "../../../../../../gen/registration/ActionFunctions";
import {translate} from "../../../../../AppUtils";
import {Texts} from "../../../../../app/Texts";

export const Register = (props) => {
	return <button
		id="register"
		onClick={registerUser}
		disabled={props.disabled}>
		{translate(Texts.registration.register)}
	</button>
}



/******* S.D.G. *******/



