/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

const ScenarioUtils = require("../ScenarioUtils");



module.exports = {
	loginDataWasNotSetInLocalStorage: async function(driver, testId) {
		return await ScenarioUtils.getValueFromLocalStorage(driver, "token") === null
	}
}



/******* S.D.G. *******/


