/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/

const ScenarioUtils = require("../ScenarioUtils");



module.exports = {
	loginDataWasSetInLocalStorage: async function(driver, testId) {
		expect(await ScenarioUtils.getValueFromLocalStorage(driver, "token")).not.toEqual(null);
	}
}



/******* S.D.G. *******/


