/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractPasswordRepetitionChangedAction from "../../../gen/password/actions/AbstractPasswordRepetitionChangedAction";

export default class PasswordRepetitionChangedAction extends AbstractPasswordRepetitionChangedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



