/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractValidateUsernameAction from "../../../gen/password/actions/AbstractValidateUsernameAction";

export default class ValidateUsernameAction extends AbstractValidateUsernameAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



