/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractValidatePasswordAction from "../../../gen/password/actions/AbstractValidatePasswordAction";

export default class ValidatePasswordAction extends AbstractValidatePasswordAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



